### PR TITLE
Taiga Biome [Podzol, mossstone and Spruce Trees]

### PR DESCRIPTION
**Pull request by Muqsit**
Done taiga Biome...
Genisys-PHP7 Binary used
Tested

### CODE REVIEW

**Comment by Muqsit** [comment]
A preview...

**Comment by Muqsit** [comment]
screenshot_2016-02-10-22-34-58

**Comment by RandomAltThingy** [comment]
Nice

**Comment by Muqsit** [comment]
Thank you ^-^

**Pull request merged**
