### PR TITLE
Omg it's 0.15.10 :)

### PR DESCRIPTION
**Pull request by RumBenCraftPE**
### Description
0.15.10 Update

### Reason to modify
just tryna help.

### Tests & Reviews

I have tested and it works. (:
Srsly it does. Pls don't deny dis.

### CODE REVIEW

**Comment by XFuryMCPE** [comment]
Still says 0.15.9 in the PocketMine.php file

**Comment by RumBenCraftPE** [comment]
Daddy Fury I know but I did rewrite that but GitHub is being a lousy bish and not adding the modified clone to the PR. I'm a nub to GitHub daddy Fury. Teach me. How do I add another file to PR? I didn't want to interrupt again by adding another PR.

**Comment by XFuryMCPE** [comment]
..., I'm not the one to be asking when it comes to that :

**Comment by TheAppleGamer** [comment]
Already a branch for 0.15.10

**Pull request closed without merging**
