### PR TITLE
Fixes addWindow() not working properly #1594

### PR DESCRIPTION
**Pull request by Muqsit**
### Description
Fixes addWindow() not working most of the time.

### Reason to modify
I might sound dumb but I think int tags aren't working properly? Removing them literally fixed it...well at least for me!

### Tests & Reviews
After removing ints, addWindow() started to work flawlessly every single time. I am still *not sure* if this was the only reason behind addWindow() not working. I've tried adding a chest window and it worked.

### CODE REVIEW

**Comment by Muqsit** [comment]
Hmm let me test it with every tile.

**Comment by dschwartz783** [comment]
@Muqsit If that's all it took to fix this, then I think we can safely say... #phpsucks

**Comment by ishitatsuyuki** [comment]
@dschwartz783: no, if this really have effect, that's due to int being a built-in type (non-object), and thus cannot contain null.

**Comment by dktapps** [comment]
Hmm. This shouldn't affect anything regardless because forceId is not used 99% of the time anyway. Peculiar.

**Comment by Muqsit** [comment]
Yep. And confirmed. addWindow() worked 34 times in a row so I think it works every time now.

**Comment by robske110** [comment]
Wait as far as i can see it should just be :float

**Comment by robske110** [comment]
No lol

**Comment by dktapps** [comment]
@robske110 what? WindowIDs are _always_ ints.

**Comment by robske110** [comment]
Was confused by %99

**Comment by robske110** [comment]
But why does this make it work again? I'll try it with float. If that works, we have a problem

**Comment by Muqsit** [comment]
I don't get it too... but why do you think float is gonna work?

**Comment by robske110** [comment]
Because apperently force convertinf the number to int breaks it. How about some var_dumping?

**Comment by ishitatsuyuki** [comment]
@robske110: int probably rejects null.

**Comment by robske110** [comment]
I'll just conduct some tests, ok? Will report what i found out.

**Comment by dktapps** [comment]
I think we're running around in the dark here. I find it unlikely that this is the real cause or solution.

**Comment by ishitatsuyuki** [comment]
Code Review +1.
If null is converted into int, it won't be compared correctly with === null.

**Comment by ishitatsuyuki** [comment]
Oh, wait: the return value should be enforced to be int however, and please also correct the documentation.

**Comment by robske110** [comment]
Yep, you got it. Due to forcing it to int and then being type strict (===) it fails. And this is why i don't like using this new php7 shit.

**Pull request closed without merging**
