### PR TITLE
add loop.cmd

### PR DESCRIPTION
**Pull request by tigerza117**
### Tests & Reviews

Auto restart on server close 
How to use 
edit line 5 and line 20 "19132" to you servre port
work :)

### CODE REVIEW

**Comment by jojoe77777** [comment]
`Starting your ImagicalMine server.`
*facepalm*

**Comment by daniktheboss** [comment]
Lmao

**Comment by tigerza117** [comment]
-.-

**Comment by dktapps** [comment]
Also, this script fails hard in most circumstances. That's why we never added this ourselves.

**Comment by ABAxStorm** [comment]
This would've also break a lot of servers which go through hosting services, since a lot of people are unable to update Genisys themselves with the services.

**Pull request closed without merging**
