### PR TITLE
Added power, unbreaking, flame bow enchantment effects

### PR DESCRIPTION
**Pull request by Tarik02**
### Description

This PR adds some enchantment effects.

### Reason to modify

I'm want to help you with developing of Genisys.

### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by Tarik02** [comment]
// TODO: Bow punch

**Comment by dktapps** [comment]
This is already underway by one of our development team. Unsolicited PRs with lots of changes are unwelcome. Please desist.

**Comment by dog194** [comment]
Thanks for contribution. coz there are still something wrong with bow and arrow, we need to fix it at the same time. But when it's time to add enchantment for bow, i will take your code as a reference. XD

**Comment by Tarik02** [comment]
@dog194, ok.

**Pull request closed without merging**
