### PR TITLE
Made Custom Enchantments possible

### PR DESCRIPTION
**Pull request by KairusDarkSeeker**
### Description
I've made this pull request to make CustomEnchantments possible for a plugin

### Reason to modify

Yes
Yes
I changed private __construct to a public function and changed protected static $enchantments to a public static variable

### Tests & Reviews
I have tested the code and it works perfectly with a custom enchants plugin

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
I think this is barely needed and considered as anti-pattern. -1

**Comment by KairusDarkSeeker** [comment]
@ishitatsuyuki why?

**Comment by ishitatsuyuki** [comment]
Explain what you are **really** trying to do instead of concepts. The reason to modify is insufficient.

**Comment by KairusDarkSeeker** [comment]
@ishitatsuyuki I made the PR to make the plugins able to access the Enchantments then all people will now be able to create a custom enchantment plugin by not making a Modder genisys server phar file :)

**Comment by ishitatsuyuki** [comment]
Well, a foolish idea. They won't work without server modification, not only this class.

**Comment by KairusDarkSeeker** [comment]
@ishitatsuyuki okay...............................................................

**Pull request closed without merging**
