### PR TITLE
Temporary fire breaking fix.

### PR DESCRIPTION
**Pull request by IrishUHC**
This is tested and it does work. Like the title says it temporarily fixes breaking fire.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
No, you're modifying the wrong file.

**Comment by IrishUHC** [comment]
My bad, let me fix that :)

**Comment by ishitatsuyuki** [comment]
No, you're not testing and even worse, you shouldn't change the event code.

**Comment by IrishUHC** [comment]
I am trying to figure out what to put it under, sorry for the inconvenience. First time fixing stuff like this :P

**Pull request closed without merging**
