### PR TITLE
Fixes: "You have no permission to use Command Selector" :3

### PR DESCRIPTION
**Pull request by Muqsit**
temp fix

### CODE REVIEW

**Comment by Muqsit** [comment]
Approved!

**Comment by Muqsit** [comment]
Approved!

**Comment by flaxues** [comment]
Finally

**Comment by Muqsit** [comment]
nvm i found the bug

**Comment by flaxues** [comment]
?

**Comment by Muqsit** [comment]
#808

**Comment by Muqsit** [comment]
#808

**Pull request closed without merging**
