### PR TITLE
Fix permission for start.sh

### PR DESCRIPTION
**Pull request by gaoyichuan**
Add the execute premission.

### CODE REVIEW

**Comment by GalvinGao** [comment]
phhh... What are you did...... nothing changed...

**Comment by CrayonDing** [comment]
Please check out your push.

**Comment by gaoyichuan** [comment]
I think you should have a carefully look...
start.sh 100644 → 100755
(file mode changed)

**Comment by gaoyichuan** [comment]
@CrayonDing

**Comment by CrayonDing** [comment]
Aha.Sorry

**Pull request merged**
