### PR TITLE
Fix bug with empty creative inventory after full reload of server

### PR DESCRIPTION
**Pull request by mixailenko5**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Look likes a hack. Can you explain?

**Comment by mixailenko5** [comment]
@ishitatsuyuki  If player in creative mode, then his items updates and he can see their. I fix this bug in pm++. And i am creating server on Genisys now. And I saw this bug

**Comment by mixailenko5** [comment]
I write /save-all and "sudo reboot" (in terminal). And palyers who was in creative mode dont see their items in creative inventory. Creative becomes completely empty. And this code fix this bug.

**Comment by ishitatsuyuki** [comment]
Is setting the gamemode necessary? It can cause additional glitches.

**Comment by PeratX** [comment]
Have tested the code without this? I think this will not happen...

**Comment by mixailenko5** [comment]
@PeratX I decided to rest from PluginMaker. And i started create the srever with my mini game. But i saw bug with creative items. After rebooting system all items disappeared. I changed gamemode to survival and to creative (/gamemode 0   /gamemode 1). And it is worked. And i write this code, who fixed this bug.

**Comment by mixailenko5** [comment]
Sorry for my english, but this codefix bug with loss of items on creative inventory

**Comment by PeratX** [comment]
But you can see PlayerInventory.php . We already send creative inventory!(no lose)

**Comment by mixailenko5** [comment]
@PeratX i saw. But i saw bu today too. And you decide take or not take this code

**Comment by PeratX** [comment]
I will try to find better solution

**Pull request closed without merging**
