### PR TITLE
French Translation Finish

### PR DESCRIPTION
**Pull request by Bananaunymous**
Added French translation

### CODE REVIEW

**Comment by dktapps** [comment]
Squash your commits, then. And don't PR spam.

**Comment by gaoyichuan** [comment]
Don't use github's editor

**Comment by dktapps** [comment]
Use Google.

**Comment by Bananaunymous** [comment]
I don't know if i did the right thing ... I'm new on github

**Comment by gaoyichuan** [comment]
Okay, next time please use git command to make your changes.

**Comment by gaoyichuan** [comment]
+1 for this one

**Pull request merged**
