### PR TITLE
[WIP] XP autoname

### PR DESCRIPTION
**Pull request by IrishUHC**
Makes it so you don't have to type the full player name in when doing the /xp command

### CODE REVIEW

**Comment by dktapps** [comment]
Code Review -1. Reason: If you use this, the short-typed name will be shown in the resulting message instead of the actual player's name.

**Comment by IrishUHC** [comment]
I'll reformat it to show the full players name :)

**Comment by dktapps** [comment]
That looks better. Once you're done, please squash your commits by rebasing.

**Comment by IrishUHC** [comment]
I am looking at how to do that right now, please be patient while I do this because I am pretty new to Github. Thanks :)

**Comment by dktapps** [comment]
@IrishUHC no problem. If you can learn, and not throw a fit about it like some other kid did, that's good enough for me. :)

**Comment by IrishUHC** [comment]
I really messed that up, somehow from Github desktop I applied two more commits. hm.

**Comment by IrishUHC** [comment]
I followed all of the instructions from Github, but Git Bash never opened a text editor, just put all of the rebasing materials, such as pick, squash, etc. all into the console. I will keep figuring it out, please bare with me. :)

**Comment by dktapps** [comment]
Ugh. Get rid of that merge commit. Use "drop" when you rebase to get rid of those last few commits. Here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by IrishUHC** [comment]
Super sorry about that, I was and still am reading that linked page :)

**Comment by dktapps** [comment]
No problem. Take as long as you need, we're in no rush

**Comment by IrishUHC** [comment]
Ok, I do have a question. It says its supposed to open up a text editor, but all of the information just pops up in the bash?

**Comment by dktapps** [comment]
Talk in the Gitter chat so we don't spam the PR.

**Comment by IrishUHC** [comment]
okay

**Pull request closed without merging**
