### PR TITLE
Added italian language on installer

### PR DESCRIPTION
**Pull request by Mattia990**

### CODE REVIEW

**Comment by ABAxStorm** [comment]
Just a warning, this is PR spamming.

**Comment by Mattia990** [comment]
Sorry but gaoyichuan sayed to squash my commits and i tryed to do this but i can't and i added a new pull request with an only commit.

**Comment by ishitatsuyuki** [comment]
Your commit message are against the rule. You can add me as collaborator of your fork to let me modify it instead.

**Comment by Mattia990** [comment]
@ishitatsuyuki I added you as my collaborator

**Comment by ishitatsuyuki** [comment]
Our policy for translation is "let a native take a look". Do you know anyone suitable as reviewer?

**Comment by Mattia990** [comment]
But how can i delete other pull request?

**Comment by ishitatsuyuki** [comment]
Let's ship it and wait for feedback. Merging.

**Comment by Mattia990** [comment]
ok, thanks

**Pull request merged**
