### PR TITLE
15.6 update

### PR DESCRIPTION
**Pull request by xZeroMCPE**
### Description

15.6 update, doesn't really do anything, and this PR is really simple. You can prob close this PR and do it yourself!

### CODE REVIEW

**Comment by NycuRO** [comment]
0.15.6 is released? :/

**Comment by TheAppleGamer** [comment]
No need to even edit that lol

**Comment by xZeroMCPE** [comment]
@TheAppleGamer  Yeah! lol

**Comment by ZedCee** [comment]
You don't need to edit that to connect.  We'll get around to it when it's necessary.  

In the meantime, it's always recommended to wait before updating to ensure we can flesh out any new/potential bugs.  

Also before submitting any further PRs, please read the contributions guidelines; You have edited using the GitHub editor, which is highly recommended against.

**Pull request closed without merging**
