### PR TITLE
Create ces.ini (czech)

### PR DESCRIPTION
**Pull request by ondraczsk**
New czech lanauge, i also create pull request for src/pocketmine/wizard/InstallerLang.php to set up.

### Description

New czech lanauge i also create PR for github.com/iTXTech/Genisys/pull/2289

### CODE REVIEW

**Comment by ondraczsk** [comment]
why...

**Comment by ondraczsk** [comment]
This I spent one hour

**Comment by dktapps** [comment]
#2289 why make two separate PRs? It's irritating.

**Comment by ondraczsk** [comment]
sorry

**Pull request closed without merging**
