### PR TITLE
Fixed entity rotation issues

### PR DESCRIPTION
**Pull request by jojoe77777**
Tested this and it works. Fixes entity rotation issues with plugins and
maybe mobs from spawn eggs. Copied from PocketMine, written by intyre

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Please use `git cherry-pick` or `git commit --author`.

**Comment by jojoe77777** [comment]
git doesn't work for me, I use GitHub Desktop. What's wrong?

**Comment by ishitatsuyuki** [comment]
Learn to use commands; this is a polite way to copy other's commit.

**Comment by jojoe77777** [comment]
> Learn to use commands; this is a polite way to copy other's commit.

Sorry, I can't, and intyre doesn't mind...

**Comment by ishitatsuyuki** [comment]
Closing this; will manually cherry pick later.

**Pull request closed without merging**
