### PR TITLE
Fix events. Added PlayerBucketEmptyEvent

### PR DESCRIPTION
**Pull request by mixailenko5**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code Review -1: I think you're doing it opposite. Please test before posting.

**Comment by jojoe77777** [comment]
I think that line should be left how it is, and the other PlayerBucketFillEvent should be changed to PlayerBucketEmptyEvent.

**Comment by dktapps** [comment]
@jojoe77777 if you read the code carefully, it is in the right place. The code is admittedly very confusing to read though. `$targetBlock` is what's currently contained in the bucket.

**Comment by ishitatsuyuki** [comment]
@dktapps What you are trying to explain are right but your conclusion is wrong. Read the code again.

**Comment by dktapps** [comment]
@ishitatsuyuki as I said, the code is confusing. @jojoe77777 is right: the event calls are the wrong way round.

**Comment by dktapps** [comment]
@ishitatsuyuki there seems to be an issue with pullapprove

**Comment by ishitatsuyuki** [comment]
@dktapps Yes, I'm investigating.

**Comment by ishitatsuyuki** [comment]
@dktapps I have finally fixed the pull approve. You can play something on this one, however please note that actions on your own PR will be ignored.

**Comment by dktapps** [comment]
Including discussed changes in #1145 for the sake of simplicity.

**Pull request closed without merging**
