### PR TITLE
Added noClip to player

### PR DESCRIPTION
**Pull request by Tarik02**
### Description

This adds property noClip, methods setNoClip, getNoClip to Player class.

### Reason to modify

I'm want to make players spectators that can go such as normal players. Spectators very inconvenient in PE, but works good in Win10E.

### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by XFuryMCPE** [comment]
Better merge your commits, or they're gonna get pissed at you :laughing:

**Comment by dktapps** [comment]
@XFuryMCPE Shut up.

**Comment by dktapps** [comment]
However annoying he is, he's correct. Please squash your commits.

**Comment by ishitatsuyuki** [comment]
Looks good, and see above.

**Comment by daniktheboss** [comment]
Lol

**Comment by daniktheboss** [comment]
Oh my... thanks for the unban.. won't spam anymore

**Comment by robske110** [comment]
you need to set no clip on spectator mode though too! 
DO NOT MERGE: BREAKS SPECTATOR MODE

**Comment by dktapps** [comment]
What in the world are you doing?

**Comment by dktapps** [comment]
Okay, this is getting ridiculous. Closing.

**Comment by XFuryMCPE** [comment]
LOL

**Pull request closed without merging**
