### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
### Description
This pull request updates Korean translation for new Genisys update.

### Reason to modify

Updated installer kor.ini, main kor.ini and genisys_kor.yml.

### Tests & Reviews
I tested it and it worked fine.

### CODE REVIEW

**Comment by ParkChanSol** [comment]
한번에 커밋해주세요...

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 한번에 커밋했는데요?? (I did commit at once?)
(The reason why I created new pull request even it's kind of spammy stuff is I failed squashing commits)

**Comment by PeratX** [comment]
+1
Reviewed the properties.

**Comment by dktapps** [comment]
+1 and merge.

**Pull request merged**
