### PR TITLE
Fully working slimeblocks :)

### PR DESCRIPTION
**Pull request by Muqsit**
Does this automatically add slimeblocks' crafting recipe?

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Title is misleading. I thought you meant they bounce you and do all that stuff

**Comment by gaoyichuan** [comment]
Please just do one thing in a single Pull Request.

**Comment by Muqsit** [comment]
Wait...they DO bounce and stuff!

**Comment by gaoyichuan** [comment]
I told you to do one thing and only one thing in one PR so open another one plz

**Comment by PocketKiller** [comment]
because you added camera @Muqsit

**Comment by TheDiamondYT1** [comment]
Why one thing in a single pull request? I understand if you said one commit in a pull request, but seriously - its just wasting people's time telling them to make a PR for every feature they want to add.

**Comment by gaoyichuan** [comment]
@TheDiamondYT1 No, that's not a waste of time. A single PR for a single feature is a convience for the commiter and the developers since we can review the code without trouble.

**Pull request closed without merging**
