### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by MrGenga**
### Description

Fix

### Reason to modify

Fix crash
### Tests & Reviews

Fix

### CODE REVIEW

**Comment by dktapps** [comment]
Really? There seem to be a lot of crashes. *HAVE YOU PROPERLY TESTED THIS TIME?*

**Comment by dktapps** [comment]
No detail whatsoever and the code quality does not meet our guidelines. Closing.

**Comment by MrGenga** [comment]
@dktapps now I tested, no crashs, client doesn't freezes

**Comment by MrGenga** [comment]
@dktapps you looks like idiot, you closed my fix PR, I TESTED IT AND IT WORKS!

**Comment by dktapps** [comment]
**No detail whatsoever**

**Comment by gaoyichuan** [comment]
Even it works, your commit message and description is a mess

**Pull request closed without merging**
