### PR TITLE
Nuke horrible AI. Close #1842

### LINKED ISSUE #1842: [VOTE] MyOwnWorld based AI removal
This is a poll for the future of the MyOwnWorld based AI currently in Genisys. I want to remove the current AI.

### Reasons:
- because it's a disgusting, buggy mess, not worthy to be included in our server software
- it's some of the worst code I've ever had the misfortune to work with
- it's not GPL licensed and therefore should not be included in a GPL-licensed software
- if you want MOW AI, you can use MOW itself (https://github.com/zzm317/MyOwnWorld).

### Wait, the AI will be removed?
The current horrible AI will be replaced at a later date by a more advanced, much cleaner and nicer AI. I have plans to write new AI in the future.

### How do I vote?
Simply add a reaction to this issue.
- :+1: : Remove the AI
- :-1: : keep it

### PR DESCRIPTION
**Pull request by dktapps**
### Description
:spew: Removing this horrible AI from our server core.

### Reason to modify
- Think twice before modifying: is it the best way? will it break things? 
  - You can be damn sure it'll break things. No mob AI or mob generation
- Have you made sure that there is actually a problem before trying to fix it?
  - Do I really need to answer that?
- Explain the logic behind your changes - WHY and HOW what you have done works
  - Deleting files never felt so good.

I put up a vote at #1842.  After 2 days it hit a 16:1 majority to get rid of it. I think it should be gone. I may include the horrible mess in a plugin if people _really_ want to use it. 

### Tests and reviews
 I have tested the code and it works.

### CODE REVIEW

**Comment by dktapps** [comment]
TODO: Nuke CallbackTask

**Comment by TheAppleGamer** [comment]
If I could merge it here I would do it lol

**Comment by PeratX** [comment]
+1

**Comment by Muqsit** [comment]
I'll approve this when there's a pending PR for the new AI xD

**Comment by dktapps** [comment]
@Muqsit (^_^) that makes things awkward.

**Comment by TheDiamondYT1** [comment]
Ikr

**Comment by TheDiamondYT1** [comment]
Cant you just merge yourself @dktapps

**Comment by dktapps** [comment]
I can, but I prefer to follow protocol.

**Comment by XFuryMCPE** [comment]
o wow, this also saves me a few kb of space on my machine, plz merge

**Comment by Muqsit** [comment]
+1 hope the new ai fixes bugs with ENTITY_NO_AI tag.

**Comment by Muqsit** [comment]
@dktapps You have to fix some things up xD
You forgot to remove ```if($this->getLevel()->getServer()->aiConfig["zombie"] != 2)```
```php
Notice: Undefined property: pocketmine\Server::$aiConfig in /pocketmine/entity/Zombie.php on line 123.
```
And in /pocketmine/entity/FlyingAnimal.php, you forgot to remove everything that comes under...
```php
if ($this->willMove(100) and $this->getLevel()->getServer()->aiEnabled) {
```

**Comment by dktapps** [comment]
My bad, will fix it later.

**Pull request merged**
