### PR TITLE
Fix drop item from W10E.

### PR DESCRIPTION
**Pull request by xpyctum**

### CODE REVIEW

**Comment by Tee7even** [comment]
Please read it carefully.
At line 3194: 
```
$item = $**thos**->inventory->contains($dropItem->item) ? $dropItem->item : $this->inventory->getItemInHand();
```

Logs:
```
[19:32:19] [Server thread/INFO]: Tee7even joined the game

Notice: Undefined variable: thos in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Trying to get property of non-object in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Undefined variable: thos in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Trying to get property of non-object in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Undefined variable: thos in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Trying to get property of non-object in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Undefined variable: thos in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194

Notice: Trying to get property of non-object in phar://C:/Users/Tee7even/Desktop/mc-pocket/PM/Genisys.phar/src/pocketmine/Player.php on line 3194
[19:32:21] [RakLibServer thread/NOTICE]: Blocked 100.107.105.106 for 5 seconds
[19:32:27] [Server thread/INFO]: Tee7even left the game
```

**Comment by xpyctum** [comment]
@Tee7even whoops

**Comment by thebigsmileXD** [comment]
uhm.. this will not prevent that win10 drops items.

The drop event is called 4 times. thats the amount of slots in the crafting menu in win 10 inventory

**Comment by xpyctum** [comment]
@thebigsmileXD client side bug?

**Comment by thebigsmileXD** [comment]
Internal handling and kind of missing packet bug

**Pull request merged**
