### PR TITLE
Better Sand and Plain Biome

### PR DESCRIPTION
**Pull request by Muqsit**
- Added Dead Bush and Cactus to Sand biomes 
- Added Ponds to Plain Biomes (with LilyPad generation)

P.S. I think it's bad to add more files to PocketMine, so I'll try reducing the number.
screenshot_2016-02-14-16-28-11

### CODE REVIEW

**Comment by Muqsit** [comment]
screenshot_2016-02-14-15-26-14

**Comment by Muqsit** [comment]
Tell me whether o should make another pullrequest for generating more and different kinds of flowers in PlainBiomes (just like in the first picture)

**Comment by PocketKiller** [comment]
\#BiomeLove

**Comment by Muqsit** [comment]
XD

**Pull request merged**
