### PR TITLE
Enchantment Max Level condition

### PR DESCRIPTION
**Pull request by Infernus102**
### Description

Enchantment max level condition

### Reason to modify

So players won't enchant to level outside the given max level like 999...
### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by jojoe77777** [comment]
> if($args[2] > $maxlevel and $args[2] <= 0){

> I have tested the code and it works.

So if it's greater than the max, AND less than 0, it's valid?

**Comment by ishitatsuyuki** [comment]
Hey, you are subject to a ban if you continue to post such terrible code. Please review the contribution guidelines.

**Comment by ishitatsuyuki** [comment]
> * No translation text.
> * GitHub editor.
Squash and change it to a descriptive commit message.

**Comment by Infernus102** [comment]
@iPocket what?

**Comment by Infernus102** [comment]
do i have to translate each language?

**Comment by Infernus102** [comment]
:) 👍

**Comment by ishitatsuyuki** [comment]
Wait, this one is a hybrid of space and tabs.

**Comment by ishitatsuyuki** [comment]
Good point. I also prefer inlining the maxLevel. @Infernus102, it's your turn, do a rebase.

**Comment by Infernus102** [comment]
idk how to @ishitatsuyuki

**Comment by KairusDarkSeeker** [comment]
Some enchantments' levels are only 1

**Comment by KairusDarkSeeker** [comment]
So, should I revert this?

**Comment by iPocket** [comment]
no

**Pull request merged**
