### PR TITLE
Update Protocol 0.15

### PR DESCRIPTION
**Pull request by SuperKali**
Protocol 0.15

### CODE REVIEW

**Comment by xxFlare** [comment]
@SuperKali This won't update the mechanics, just this allows clients to come (but it wont work) without proper changes to Login Packets.

**Comment by Muqsit** [comment]
Oh, who even noticed the protocol had changed in 0.15?

**Comment by daniktheboss** [comment]
when is the official 0.15 phar coming out?

**Comment by Muqsit** [comment]
As soon as it could!

**Comment by daniktheboss** [comment]
I read there is a 1.2dev version? But that one doesn't let people join. :(

**Pull request closed without merging**
