### PR TITLE
Add Ender chest

### PR DESCRIPTION
**Pull request by JackNoordhuis**
### Description
Add the basic vanilla Ender Chest implementation

### Reason to modify
Ender Chests are a vanilla feature commonly used by servers.

### Tests & Reviews
Thoroughly tested by myself, works exactly like vanilla.

### CODE REVIEW

**Comment by Muqsit** [comment]
Crafting Recipe?

**Comment by JackNoordhuis** [comment]
@Muqsit Never edit the auto-generated files by hand. All the crafting recipes should also be up to date from the auto-generated data anyway.

**Comment by dktapps** [comment]
Nice, will test this later.

**Comment by dktapps** [comment]
@Muqsit for reference...

From 67c24befd5d8b4f09c0f66cccbbaae1e64d4d8e3 Mon Sep 17 00:00:00 2001
From: "Dylan K. Taylor" <odigiman@gmail.com>
Date: Sat, 31 Dec 2016 16:33:53 +0000
Subject: [PATCH] Auto-generated crafting and creative inventory data for 1.0.0.16, do not modify by hand

**Comment by JackNoordhuis** [comment]
This is available for testing over on psn.conflictpe.net if you want to try it out.

**Pull request merged**
