### PR TITLE
Fix Korean Grammer, and some word change to simply

### PR DESCRIPTION
**Pull request by ParkChanSol**
### Description

Fix Korean
### Reason to modify

 Some word fix
### Tests & Reviews

It doesn't need test

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Invite your Korean friend for a review.

**Comment by ParkChanSol** [comment]
@Johnmacrocraft Plz check Korean Grammer
한국 문법하고 단어 간단하게 했는데 체크좀 해주세요

**Comment by ParkChanSol** [comment]
@TanToan99 Are you Korean?

**Comment by ParkChanSol** [comment]
@ishitatsuyuki @Johnmacrocraft check Korean

**Comment by dktapps** [comment]
Is everyone happy with this?

**Comment by ParkChanSol** [comment]
@dktapps maybe. It improve that some word change to easy word

**Comment by Johnmacrocraft** [comment]
@dktapps I think I am :) (If you're confused with this, I just answered to you) (If this is kind of spam sorry)

**Pull request merged**
