### PR TITLE
Fix cave usage "ommands.cave.usage"

### PR DESCRIPTION
**Pull request by TheAppleGamer**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
You didn't fill out the template and there is a typo in the title. Fix it.

**Comment by ishitatsuyuki** [comment]
And you're wrong and it means you haven't test it. Next time you spamming you will get banned.

**Comment by TheAppleGamer** [comment]
Man ClearSky github was right, you guys are harsh

**Comment by ishitatsuyuki** [comment]
Dude that's right that only people like you, who submits wrong code or issues does complain.

**Comment by ZedCee** [comment]
@TheAppleGamer Harsh?  This is a development website.  We focus on development.  There are things you do to keep it professional and keep things moving forward, of which you barely put an effort in or did the bare minimum.  
Imagine this were a job and a business, what's more efficient?  Upon first glance, we don't know what you actually did to "fix" the command and the PR looks woefully unprofessional and immature.  Zero description, typos in the title.

Lastly, by using github to make the commits it proves that it is untested.  If it were tested, you might note the errors that arise from this "fix".  This wastes time of your own and others.

If we wanted PRs like this, we wouldn't offer a template for submitting them.  The template and proper form of submission helps expedite the process of improving Genisys, prevent erroneous code and avoid guess work.  It also ensures the users and developers can follow along with what's going on with the software.

**Pull request closed without merging**
