### PR TITLE
Update Korean language

### PR DESCRIPTION
**Pull request by ParkChanSol**
### Description

Fix some Korean

### Reason to modify

Since first Korean translate "!" and "." doesn't matching eng.ini

I tested

### CODE REVIEW

**Comment by ParkChanSol** [comment]
@Johnmacrocraft 그럼 삭제할게요

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 에...? 왜요? 그냥 수정해도 될 것 같은데

**Comment by ParkChanSol** [comment]
@Johnmacrocraft 귀찮은거 좀 수정했더니 옆에서 잔소리 들려서요

**Comment by Johnmacrocraft** [comment]
@ParkChanSol XD... 그냥 제 의견입니다. 잔소리로 들으시면 어떡해요! 하지만 Installer 폴더의 kor.ini는 예전에도 말했듯이 제가 이전에 실수를 냈습니다. 그거는 나중에 저보다 먼저 다시 Pull Request를 만들거나 하시면 수정 부탁 드립니다.

**Comment by JackNoordhuis** [comment]
There should be no accreditation there in the first place, this is an open source project and your contributions are listed by GitHub. If we credited everyone for everything they contributed to Genisys then it'd be even messier than it already is.

**Comment by Johnmacrocraft** [comment]
@JackNoordhuis Yea, we know, but the reason why we added that is (Yea, like you said it was actually added as credit) to help people if they need to contact us with Korean translation. We'll remove it (After discussing with @ParkChanSol).

**Pull request closed without merging**
