### PR TITLE
Real fix sendTIP

### PR DESCRIPTION
**Pull request by robske110**
This fix is actually working, while not breaking compatibility for plugins

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Well, this is just a hack though.

**Comment by ImagicalGamer** [comment]
Yes but @ishitatsuyuki it works (kinda) many plugins use Tip and Popup so they can send multiple messages, this would fix compatibility for those.

**Comment by PhilipphatesPHP7** [comment]
it would work!

**Comment by ishitatsuyuki** [comment]
Your neighbor PR has a more beautiful patch, but closed since it's just a hack.

**Comment by PhilipphatesPHP7** [comment]
ClearSky has the same code for sendTip() and it nicely works !

**Comment by ishitatsuyuki** [comment]
It doesn't matter if it works or not. This is a hack, using a deprecated thing in PE.

**Comment by PhilipphatesPHP7** [comment]
ohh please :c

**Comment by PhilipphatesPHP7** [comment]
Yes why do somthing that works ?
Have I change to ClearSky ?

**Comment by robske110** [comment]
I do know that this is a hack, but PeratX's hack doesn't even WORK?!

**Comment by ishitatsuyuki** [comment]
Okay, I will revert that...

**Pull request closed without merging**
