### PR TITLE
Add FastPlayerListPacket

### PR DESCRIPTION
**Pull request by MrGenga**
### Description
<br />
<br />Fix PlayerListPacket bug in Nemisys.
<br />
<br />### Reason to modify
<br />
<br />I just replaces original PlayerListPacket with FastPlayerListPacket :3
<br />### Tests & Reviews
<br />
<br />
<br />
<br />
<br />
<br />There is only replaces MCPE packet with Synapse identical, I think it doesn't need a lot of tests.
<br />

### CODE REVIEW

**Comment by MrGenga** [comment]
@dktapps @PeratX

**Comment by ishitatsuyuki** [comment]
Have you tested this? I and Dylan don't use Nemisys and are reluctant to setup it for test.

**Comment by dktapps** [comment]
Seems a slight lack of activity from the people responsible for this project. Please be patient. I know next to nothing about Nemisys, I don't use it and it's not my field.

**Comment by MrGenga** [comment]
@PeratX and @boybook knows

**Comment by Yoyu666** [comment]
what is this do?

**Comment by Tarik02** [comment]
+1

**Comment by Tarik02** [comment]
@Yoyu666, this fixes client freeze when playing though SPP and click back button.

**Comment by PeratX** [comment]
Looks good. +1

**Comment by ishitatsuyuki** [comment]
PeratX, filling a slot for you. Merge at your risk.

**Comment by PeratX** [comment]
What do you mean.

**Comment by dktapps** [comment]
A supplementary (untested) plus-one I think he means.

**Comment by PeratX** [comment]
Tested. Working.

**Comment by dktapps** [comment]
What happened to the PR formatting? Dear God. Well, whatever.

**Comment by SleepSpace9** [comment]
I got an error on login now:

```
[15:44:23] [Server thread/INFO]: PillePalle[/87.179.90.180:23456] [ClientID: -9125418660827245104] logged in with entity id 1 at (Lobby, 17.5207, 5.4, -26.1701)

Notice: Undefined variable: sendTo in phar:///usr/games/pocketmine-lobby/Genisys_1.2dev.phar/src/synapse/network/protocol/spp/FastPlayerListPacket.php on line 29
[15:44:24] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putUUID() must be an instance of pocketmine\utils\UUID, null given, called in phar:///usr/games/pocketmine-lobby/Genisys_1.2dev.phar/src/synapse/network/protocol/spp/FastPlayerListPacket.php on line 29" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream" at line 182
[15:44:24] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[15:44:24] [Server thread/EMERGENCY]: Please upload the "/usr/games/pocketmine-lobby/crashdumps/CrashDump_Sat_Aug_20-15.44.24-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[15:44:24] [Server thread/INFO]: Disabling SimpleAuth v1.7.1
...

**Comment by dktapps** [comment]
@SleepSpace9 Please open a separate issue and reference this PR.

**Pull request merged**
