### PR TITLE
YAML ban system

### PR DESCRIPTION
**Pull request by FaigerSYS**
Rewrite ban system to YAML format

### CODE REVIEW

**Comment by FaigerSYS** [comment]
Tested, works properly. Also I want to create updater for old version of ban list

**Comment by dktapps** [comment]
Do not use the web editor!

**Comment by FaigerSYS** [comment]
@dktapps , OK. Must I re-edit those files?

**Comment by ishitatsuyuki** [comment]
Before reviewing, please consider if it worth such a heavyweight and space-pain format.

**Comment by Tarik02** [comment]
-1. Not the best implementation and better to switch between yaml and old ban system.

**Comment by FaigerSYS** [comment]
I will merge it to new PR

**Pull request closed without merging**
