### PR TITLE
Added PlayerJumpEvent

### PR DESCRIPTION
**Pull request by Tarik02**
### Description

Added PlayerJumpEvent, useful for plugins.

### Reason to modify

I'm want to use this event in my anti-cheat and other plugins.

### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by XFuryMCPE** [comment]
There's no way to use it, you didn't even add any functions to the event.

**Comment by dktapps** [comment]
@XFuryMCPE How about getting your facts straight before making derogatory comments about others' work? I might add that at least he took the time to learn GIT instead of complaining and asking others to do his work for him. 

This would act as a notification for plugins.

**Comment by gaoyichuan** [comment]
This should waste a lot of resources.

**Comment by ishitatsuyuki** [comment]
I don't think this waste resources, but however it's incomplete. No cancel function is provided.

**Comment by dktapps** [comment]
@ishitatsuyuki you wouldn't be able to cancel it anyway. That's client handled.

**Comment by MrGenga** [comment]
@dktapps no you can, just setMotion (0, -$jumpHigh, 0)

**Comment by XFuryMCPE** [comment]
@dktapps I don't see why you're so picky about whether git is used or not. It's not the end of the world if git isn't used, 'oh no, there are 2 commits for one feature', who cares??? Half the people downloading this don't even use GitHub or look at the commits.

**Pull request closed without merging**
