### PR TITLE
Fix underwater breath

### LINKED ISSUE #2343: Breath underwater
#### Issue description

Breath underwater is decreasing way too fast
#### Steps to reproduce the issue

Just go underwater
#### OS and versions

* Genisys:Genisys-1ed05b7
* PHP:7.0.14
* Server OS:Win7
* Game version: 1.0.0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

### PR DESCRIPTION
**Pull request by diamond-gold**
### Description

To fix #2343 

### Reason to modify

Fix #2343, player's breath is decreasing way too fast

### Tests & Reviews

Tested the code and it works correctly with enchantment and without enchantment

### CODE REVIEW

**Comment by dktapps** [comment]
👍

**Comment by Muqsit** [comment]
L198:
You declare a variable to be an alias of
400 + $EnchantL * 300

L200:
You don't use the variable at all. You rather type in 400 + $EnchantL * 300. The variable declaration was hence useless.

Why does it have to be 400 + $EnchantL * 300, by the way?

**Comment by Muqsit** [comment]
L199: Code formatting..
I think there's a much better way to write this. If you overview it, you'll find out how much of code have you repeated. Avoid repetition to its best.

**Comment by diamond-gold** [comment]
400 + $EnchantL * 300
Its by default 20 seconds, 400 ticks, and increases 15 seconds(300 ticks) per level

**Pull request merged**
