### PR TITLE
Bumped to 0.14.3, closes #978

### LINKED ISSUE #978: MCPE UPDATE
This isnt an issue really but just wanted to let ya'll know that MCPE 0.14.3 is out and hoping you guys could add support to it ASAP? Thank you.

### PR DESCRIPTION
**Pull request by jojoe77777**
This is all in one pull request unlike #979 and #980

### CODE REVIEW

**Comment by gaoyichuan** [comment]
Have you tested this?

**Comment by jojoe77777** [comment]
Yes

**Comment by gaoyichuan** [comment]
+1 wait for another team member to merge it

**Comment by PeratX** [comment]
+1

**Comment by SuperKali** [comment]
Pls fix

**Pull request merged**
