### PR TITLE
Why on earth does Liquid extend Solid? Fixes #1018

### LINKED ISSUE #1018: Water does not naturally generate
#### Issue description
A game-breaking world generation problem which cause water to not generate. In fact; Rivers, Lakes, Swampland, etc. simply appear as some sort of weird flatlands which are, most of the time, covered in dandelions and red flowers.

#### Steps to reproduce the issue
1. Create a fresh, new world.
2. Venture a for a while until you come upon an oddly, almost perfect, flatland covered in flowers.

#### OS and versions
* Genisys: 1.1dev-391
* PHP: 7.0.3
* OS: iPhone 5S (iOS 9.3.1). Server hosted by VirtualGladiators with the Cow Egg plan.

#### Crashdump, backtrace or other files
```
Image1: https://i.imgur.com/MQa2fU4.png
Image2: https://i.imgur.com/12MLHK6.png
Image3: https://i.imgur.com/M1d0Bho.png
Image4: https://i.imgur.com/OLKyzcm.png
Image5: https://i.imgur.com/XDZ1qXq.png
Image6: https://i.imgur.com/Qvy9keW.png
Image7: https://i.imgur.com/1uMO8C5.png
```

### PR DESCRIPTION
**Pull request by dktapps**
Water bodies will now generate again in Ocean, River and Swamp biomes. Fixes #1018.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code Review +1

By the way, have you tested this?

**Comment by dktapps** [comment]
@ishitatsuyuki yes, naturally xD

**Comment by dktapps** [comment]
I thoroughly test all my changes before committing changes.

**Comment by gaoyichuan** [comment]
Review +1 & merge

**Comment by daniktheboss** [comment]
Any news on the update?

**Pull request merged**
