### PR TITLE
0.15.0 Has officially come out

### PR DESCRIPTION
**Pull request by Taki21**

### CODE REVIEW

**Comment by dktapps** [comment]
This will do nothing whatsoever. 0.15 support requires compatible protocols. All this will do is change the display version.

**Comment by Taki21** [comment]
hello im commiting more as u can see dont jump to conclusions like this....

**Comment by Taki21** [comment]
im not dumb i know that

**Comment by Taki21** [comment]
0.15.0 branch nvm

**Comment by gaoyichuan** [comment]
If you think this can work.. Then somebody will call you as a idiot

**Comment by Taki21** [comment]
0.15.0 branch nvm:
 Do u know how to read?
Apparently not...

**Comment by Taki21** [comment]
Refrenced for the protocol never mind that

**Pull request closed without merging**
