### PR TITLE
Translate Korean Finish

### PR DESCRIPTION
**Pull request by ParkChanSol**
Description

Added Korean translation. On main translation (not installer) not all stuffs are translated, but most stuffs are translated. Only few stuffs (about 5~8) are still remaing as English. P.S: Just found someone already did pull request of Korean translation, but Korean translation was already done by me (But didn't uploaded it as public using pull request). Also that user's main translation is just default frame of PocketMine-MP Korean translation, but I also translated Genisys message.

Reason to modify

Because It's annoy to add my Korean translation by downloading src folder instead of phar, it's kinda annoy to do that! So I would like to release it as public and make others use it.

Tests & Reviews

I have tested the code and it works. You can try to use this by modifying language setting

### CODE REVIEW

**Comment by dktapps** [comment]
Please do not spam PRs. You're wasting our issue ticket numbers and it's rather irritating.

**Comment by Johnmacrocraft** [comment]
@ParkChanSol Pull request description needs to be edited - Because there's some sentences which are supposed to be spoken from me (P.S ~ End).

**Comment by Johnmacrocraft** [comment]
@dktapps Please reference #1836 for information why this happened.

**Comment by ParkChanSol** [comment]
@dktapps This pull request is non spam.

**Comment by dktapps** [comment]
@ParkChanSol This is your second one. That counts as spamming. Do not do it again.

**Comment by ParkChanSol** [comment]
@dktapps You must read #1836, then you talk to me, again

**Comment by ishitatsuyuki** [comment]
lmao, your commits is full of duplicated +.

**Have you read the article on merging? You're completely wrong.**

**Comment by dktapps** [comment]
Well, this is a happy farce. What a waste of time. Come back another time when you're prepared to do it properly.

**Comment by dktapps** [comment]
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by Johnmacrocraft** [comment]
@dktapps Ok, I understand about that. You guys might say *Stop spamming and waste time for it*, then could you reopen my Korean translation pull request? All of duplicated pull request are now closed, and I think mine (#1836) doesn't have any special problems. (Problem again? Oh oh... I'm sorry for that but I tried my best)

**Comment by ishitatsuyuki** [comment]
Do a force push. We will check one that fits guidelines.

**Comment by Johnmacrocraft** [comment]
@ishitatsuyuki Excuse me does it requires Git? I never used Git (Actually once for 10 minutes lol)

**Comment by ishitatsuyuki** [comment]
This is GitHub. We don't welcome people can't use Git.

**Comment by Johnmacrocraft** [comment]
@ishitatsuyuki lol ok, I'll try to force push using Git so if I do it please consider merging it. Thanks.

**Comment by ParkChanSol** [comment]
@ishitatsuyuki Why you reopen this pull request?

**Comment by ishitatsuyuki** [comment]
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

If you guys want to be hostile each other, I won't stop you from it though.

**Comment by ParkChanSol** [comment]
I remove + in file

**Comment by ishitatsuyuki** [comment]
This looks OK. I will merge it after CI passes.

**Comment by ParkChanSol** [comment]
@ishitatsuyuki Thank you

**Comment by Johnmacrocraft** [comment]
@ishitatsuyuki I think it's too late to say, but thank you! :D

**Pull request merged**
