### PR TITLE
Fix fire breaking, fix #1091

### LINKED ISSUE #1091: Fire Bug
#### Issue description

When you try to "break" the fire, even though it doesn't show up, you can walk through it and still get burnt. 
#### Steps to reproduce the issue

Light a flint and steel on the ground, break the fire, walk through it.
#### OS and versions

* Genisys:1.1dev-a685f20
* PHP: 7.0.3
* OS: Windows 7 Professional

#### Crashdump, backtrace or other files
```
```

### PR DESCRIPTION
**Pull request by ishitatsuyuki**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Not tested. Please take a look.

**Comment by dktapps** [comment]
I've tested with the GitLab-CI build and the patch did not work for me

**Comment by ishitatsuyuki** [comment]
@dktapps I have added import. By the way, can you turn on debug and check for potential mistakes?

**Comment by dktapps** [comment]
Sure, I have debug turned on. Also, I'm running into an issue when `fire-spread` is turned on in genisys.yml. I've created issue #1096 , might this have any effect?

**Comment by dktapps** [comment]
I'm also noticing that when fire-spread is enabled, the fire keeps coming back after a second or so of breaking. Still no change in behaviour after commit 6266087

**Comment by ishitatsuyuki** [comment]
I have fixed the issue and rebased. Can you try it again?

**Comment by dktapps** [comment]
The error spam is fixed, but otherwise no change

**Comment by dktapps** [comment]
This happened, not sure how to reproduce
```
[11:00:35] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\Air not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[11:00:35] [Server thread/DEBUG]: #0 /src/pocketmine/Player(2975): spl_autoload_call(string pocketmine\Air)
[11:00:35] [Server thread/DEBUG]: #1 /src/pocketmine/network/RakLibInterface(139): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\PlayerActionPacket object)
[11:00:35] [Server thread/DEBUG]: #2 /src/raklib/server/ServerHandler(92): pocketmine\network\RakLibInterface->handleEncapsulated(string 192.168.0.102:50242, raklib\protocol\EncapsulatedPacket `..[..N....................T............, integer 0)
[11:00:35] [Server thread/DEBUG]: #3 /src/pocketmine/network/RakLibInterface(78): raklib\server\ServerHandler->handlePacket(boolean)
[11:00:35] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(164): pocketmine\network\RakLibInterface->process(boolean)
[11:00:35] [Server thread/DEBUG]: #5 /src/pocketmine/Server(2978): pocketmine\network\Network->processInterfaces(boolean)
[11:00:35] [Server thread/DEBUG]: #6 /src/pocketmine/Server(2683): pocketmine\Server->tick(boolean)
[11:00:35] [Server thread/DEBUG]: #7 /src/pocketmine/Server(2561): pocketmine\Server->tickProcessor(boolean)
[11:00:35] [Server thread/DEBUG]: #8 /src/pocketmine/Server(2076): pocketmine\Server->start(boolean)
[11:00:35] [Server thread/DEBUG]: #9 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\odigi\Downloads\Genisys\Genisys_1.1dev-03151b4.phar/, string C:\Users\odigi\Downloads\Genisys\, string C:\Users\odigi\Downloads\Genisys\plugins\, string unknown)
[11:00:35] [Server thread/DEBUG]: #10 (1): require_once(string phar://C:/Users/odigi/Downloads/Genisys/Genisys_1.1dev-03151b4.phar/src/pocketmine/PocketMine.php)
[11:00:35] [Server thread/DEBUG]: Exception in packet pocketmine\network\protocol\PlayerActionPacket 0x8eab000000000000000000000000000000540000000b0000008a00000001
[11:00:35] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\Air not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[11:00:35] [Server thread/DEBUG]: #0 /src/pocketmine/Player(2975): spl_autoload_call(string pocketmine\Air)
[11:00:35] [Server thread/DEBUG]: #1 /src/pocketmine/network/RakLibInterface(139): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\PlayerActionPacket object)
[11:00:35] [Server thread/DEBUG]: #2 /src/raklib/server/ServerHandler(92): pocketmine\network\RakLibInterface->handleEncapsulated(string 192.168.0.102:50242, raklib\protocol\EncapsulatedPacket `..\..O....................T............, integer 0)
[11:00:35] [Server thread/DEBUG]: #3 /src/pocketmine/network/RakLibInterface(78): raklib\server\ServerHandler->handlePacket(boolean)
[11:00:35] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(164): pocketmine\network\RakLibInterface->process(boolean)
[11:00:35] [Server thread/DEBUG]: #5 /src/pocketmine/Server(2978): pocketmine\network\Network->processInterfaces(boolean)
[11:00:35] [Server thread/DEBUG]: #6 /src/pocketmine/Server(2683): pocketmine\Server->tick(boolean)
[11:00:35] [Server thread/DEBUG]: #7 /src/pocketmine/Server(2561): pocketmine\Server->tickProcessor(boolean)
[11:00:35] [Server thread/DEBUG]: #8 /src/pocketmine/Server(2076): pocketmine\Server->start(boolean)
[11:00:35] [Server thread/DEBUG]: #9 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\odigi\Downloads\Genisys\Genisys_1.1dev-03151b4.phar/, string C:\Users\odigi\Downloads\Genisys\, string C:\Users\odigi\Downloads\Genisys\plugins\, string unknown)
[11:00:35] [Server thread/DEBUG]: #10 (1): require_once(string phar://C:/Users/odigi/Downloads/Genisys/Genisys_1.1dev-03151b4.phar/src/pocketmine/PocketMine.php)
```

**Comment by dktapps** [comment]
7ef485f produced some improvement. The fire doesn't come back any more, but I'm still getting set on fire when walking through that space.

**Comment by dktapps** [comment]
I added a debug message in under the condition `if($up instanceof Fire){`, and the debug message never shows...

**Comment by dktapps** [comment]
Further testing shows that it does actually work perfectly in survival, but not in creative. I assume that's to do with the fact left clicks are handled differently in creative.

**Comment by gaoyichuan** [comment]
Tested on my server and it works. +1

**Comment by dktapps** [comment]
Works for me, but only in survival mode.

**Comment by ishitatsuyuki** [comment]
Uploaded a new version which fixes side extinguishing. I still have no idea with creative.

**Comment by PeratX** [comment]
+1

**Pull request merged**
