### PR TITLE
Fix https://github.com/iTXTech/Genisys/issues/1857

### PR DESCRIPTION
**Pull request by thebigsmileXD**
### Description

Same like before, 100% tested. Only if the even't is not cancelled, particles play and the painting item drops.

### Reason to modify

Old PR was missing a "false"
### Tests & Reviews

Tested with simple entity damage cancelling plugin.

### CODE REVIEW

**Comment by dktapps** [comment]
I don't think paintings have destroy particles actually.  But other than that looks okay.

**Comment by thebigsmileXD** [comment]
i've sendt a vido into the chat group. The particles are correct, the sounds aren't 100% perfect, but close enough

**Comment by PeratX** [comment]
+1

**Comment by dktapps** [comment]
+1 and merge.

**Pull request merged**
