### PR TITLE
Rewrite deprecated methods for new PlayerInventory system

### PR DESCRIPTION
**Pull request by MrGenga**
### Description

After Windows 10 update, PlayerInventory doesn't allow to change it. But not everyone will rewrite the plugins. There is alternative to change hotbar(COMPATIBLE WITH WINDOWS 10).

### Reason to modify

Some people will not update their plugins, there is alternative to change hotbar(and held item).
### Tests & Reviews

It must works on every platform, because after Inventory fix, all hotbar slots automaticly sets to first 9 slots of inventory. My code uses this feature, and change this slots instead remapping hotbar. Please view the code before closing this PR.

### CODE REVIEW

**Comment by MrGenga** [comment]
If something wrong, say me, I will change it.

**Comment by dktapps** [comment]
Stop spamming.

**Comment by MrGenga** [comment]
@dktapps Autoclosing PRs? What the Hell?

**Comment by MrGenga** [comment]
@dktapps ok, but say me, why you close it? Whats wrong?

**Comment by MrGenga** [comment]
@dktapps I will fix it

**Comment by dktapps** [comment]
It's that way for a reason. And if you spam another PR you will be banned.

**Comment by MrGenga** [comment]
@dktapps you are looks like an idiot, because you didn't comment PR and close it. Say me - whats WRONG!?

**Pull request closed without merging**
