### PR TITLE
Not full genisys_rus.yml

### PR DESCRIPTION
**Pull request by SuperPuperSteve**
### Description

Not full genisys_rus.yml
(I will make full translation A.S.A.P.)
### Reason to modify

Adding Russian translation of genisys.yml

### Tests & Reviews

 I have tested the code and it works. 

Full translation will be sooner!

### CODE REVIEW

**Comment by FaigerSYS** [comment]
I speaking Russian too, but this PR is useless

**Comment by dktapps** [comment]
@FaigerSYS why do you say that?

**Comment by Ragnok123** [comment]
Я сделаю сам перевод.
I will make translation

**Comment by SuperPuperSteve** [comment]
@dktapps Should I make full translation after merging this PR or make it in tthis PR?

**Comment by FaigerSYS** [comment]
@dktapps , @SuperPuperSteve , sorry 😂. I just forget that there is support for other languages ​​for config

**Comment by SuperPuperSteve** [comment]
I will make full translation in another PR.

**Comment by ishitatsuyuki** [comment]
Do not spam PRs. Read the contribution guide. Continuous offenders will get banned.

**Comment by SuperPuperSteve** [comment]
@ishitatsuki I've already made changes in another branch

**Comment by ishitatsuyuki** [comment]
Your other one will also be closed according to rules.
*Do not consider spamming pull requests. If you don't know how to squash and force push, use [this site](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to learn how.*

**Pull request closed without merging**
