### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Efforto**
Something forgot...

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Please use proper commit message.

**Comment by Efforto** [comment]
Oops....

**Comment by ishitatsuyuki** [comment]
If you don't know the instructions:
git commit --amend
git push -f

**Comment by Efforto** [comment]
= =what the...I use the desktop version

**Comment by ishitatsuyuki** [comment]
Will merge manually.

**Pull request closed without merging**
