### PR TITLE
Update BrewingInventory.php

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by flaxues** [comment]
are you able to use brewing stand again with this?

**Comment by erkam2002** [comment]
I thing yes

**Comment by PocketKiller** [comment]
@flaxues No.

**Comment by flaxues** [comment]
Oh :(

**Comment by flaxues** [comment]
Jenkins is slow today :/ 8kbps

My speed is 1Gbit

**Comment by gaoyichuan** [comment]
Jenkins is slow because the server is in China.. Through the IDC where we hosted the server has the best network in China, we have GFW there..

**Comment by jasonczc** [comment]
@gaoyichuan 墙表示躺枪.事实上延迟没多大关系.上下行带宽才是问题.

**Comment by PeratX** [comment]
Sorry.This cannot fix BrewingStand

**Pull request closed without merging**
