### PR TITLE
0.15.8 version update

### PR DESCRIPTION
**Pull request by andris155**
### Description

0.15.8 version update

### Reason to modify

Mojang updated Minecraft PE.

### CODE REVIEW

**Comment by dktapps** [comment]
We update the version when a breaking change requires updates to the protocol. The protocol has not changed since 0.15.4.

**Comment by robske110** [comment]
I would just set it to 0.15.x.

**Comment by dktapps** [comment]
@robske110 you can't. The client doesn't like it when you do that.

**Comment by robske110** [comment]
Only the _NETWORK constant. CS has that at 0.15. the other string accepts anything

**Comment by dktapps** [comment]
We keep them the same for consistency,

**Comment by robske110** [comment]
this is genisys

**Pull request closed without merging**
