### PR TITLE
Make @p command selector work the way it's supposed to

### PR DESCRIPTION
**Pull request by dktapps**
@p command selector should target the player.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code Review +1

**Comment by gaoyichuan** [comment]
Code Review: Rejected
Reason: @p should select the nearest player, not the sender himself

**Comment by ishitatsuyuki** [comment]
@gaoyichuan No, try it in PC.

**Comment by dktapps** [comment]
When used by a command block, yes the nearest player is targeted. But if used by a player it will target that player unless used with arguments, which are not supported.

**Comment by dktapps** [comment]
@gaoyichuan That approve hasn't been picked up, you might need to make a fresh comment

**Comment by gaoyichuan** [comment]
Code review +1

**Comment by JUSTaMod** [comment]
how do I use the selectors in in-game commands? Is that a thing? There are no cmd blocks.

**Comment by gaoyichuan** [comment]
@JUSTaMod Just use them in-game or in the console.

**Pull request merged**
