### PR TITLE
Refinements to Bucket behaviour

### PR DESCRIPTION
**Pull request by dktapps**
Allow use of lava bucket in the Nether
Make water bucket behaviour in the Nether the same as vanilla - bucket is emptied when used, but no water placed.

### CODE REVIEW

**Comment by jojoe77777** [comment]
Change PlayerBucketFillEvent to PlayerBucketEmptyEvent and I think it will work properly. ```}elseif($targetBlock instanceof Liquid){``` means that the bucket has lava/water in it, so it's emptying the bucket, not filling it.

**Comment by ishitatsuyuki** [comment]
Just asking, is there any particles for evaporation? If you can adding it will be good.

**Comment by dktapps** [comment]
@jojoe77777 I could do that, but don't want to take credit for somebody else's work. Unless I'm told otherwise, I'll hold on to this until #1143 has been closed and then resolve conflicts afterwards.

**Comment by dktapps** [comment]
@ishitatsuyuki I think evaporation particles are already shown, yes.

**Comment by ishitatsuyuki** [comment]
I think it's OK to use that ~~stupid~~ guy's code, and if you are concerned, commit as his credentials.

**Comment by dktapps** [comment]
@ishitatsuyuki I like the way you think xD I'll attend to it shortly

**Comment by dktapps** [comment]
Added changed discussed in #1143 and rebased. I figured I might as well keep it simple - plus, not much point giving credit for code that doesn't work right.

**Comment by ishitatsuyuki** [comment]
Code review +1

**Comment by ishitatsuyuki** [comment]
@iTXTech/trusted

**Comment by gaoyichuan** [comment]
Looks good to me. Approved and merged

**Comment by ishitatsuyuki** [comment]
@dktapps: I have no idea that you have a rej ect status. Please correct it.

**Comment by dktapps** [comment]
+1

**Pull request merged**
