### PR TITLE
build 7 support

### PR DESCRIPTION
**Pull request by MrDoni98**

### CODE REVIEW

**Comment by PocketKiller** [comment]
did it change protocol?

**Comment by Driesboy** [comment]
No it work i have tested

**Comment by Driesboy** [comment]
What

**Comment by PEMapModder** [comment]
...

**Comment by Driesboy** [comment]
It work without changes

**Comment by MrDoni98** [comment]
@PocketKiller 
You know?

**Comment by PEMapModder** [comment]
Much simpler and more reliable:

```
objdump -T libminecraftpe.so | grep SharedConstants | grep Protocol

**Pull request merged**
