### PR TITLE
Add client crash info

### PR DESCRIPTION
**Pull request by ABAxStorm**
### Description

This PR adds information to the README useful for those experiencing issues with immediately crashing upon join their server due to an unsupported block being placed.

### Reason to modify

Using BlockLauncher displays the blocks as an update image of update
### Tests & Reviews

I have used this method when I ran into the same issue before.

### CODE REVIEW

**Comment by dktapps** [comment]
This sort of information should be in the wiki, not the README.

**Comment by ABAxStorm** [comment]
I understand.

**Comment by ZedCee** [comment]
This is a rather limited approach.  Only encompassing Android users.

**Comment by ZedCee** [comment]
[MCEdit](https://github.com/Khroki/MCEdit-Unified) or [PMImporter](https://github.com/Muirfield/pmimporter) can also be used.

**Pull request closed without merging**
