### PR TITLE
Fix some typo and translate new one!

### PR DESCRIPTION
**Pull request by Adam1609**

### CODE REVIEW

**Comment by Muqsit** [comment]
+1

**Comment by Striker209** [comment]
+1

**Comment by dktapps** [comment]
Please stop the spam. The +1s are for code review by developers.

**Comment by Striker209** [comment]
Sorry for the inconvenience

**Comment by ishitatsuyuki** [comment]
@Muqsit: please accept the invitation to get into the code review group. Additional notes: only action after you tested or you're so confident with the changes.

**Comment by ishitatsuyuki** [comment]
Approved.

**Pull request merged**
