### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
### Description
Added Korean translation. On main translation (not installer) not all stuffs are translated, but most stuffs are translated. **Only few stuffs (about 5~8) are still remaing as English.** _P.S: Just found someone already did pull request of Korean translation, but Korean translation was already done by me (But didn't uploaded it as public using pull request). Also that user's main translation is just default frame of PocketMine-MP Korean translation, but I also translated Genisys message._

### Reason to modify
Because It's annoy to add my Korean translation by downloading src folder instead of phar, it's kinda annoy to do that! So I would like to release it as public and make others use it.

### Tests & Reviews
I have tested the code and it works.  You can try to use this by modifying language setting

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
To Genisys developer team: This pull request also contains genisys_kor.yml which is sightly based on #1837. The user who uploaded pull request of that allowed me to retranslate genisys.yml instead of his (her) file.

**Comment by ishitatsuyuki** [comment]
Please don't make two and collaborate instead. That's one main usage of git.

**Comment by Johnmacrocraft** [comment]
@ishitatsuyuki No, I can tell you how this happened:
1. I added new pull request (this) without knowing someone already did that.
2. Found someone (@ParkChanSol) already did this, but that user's translation was just default frame of PocketMine Korean translation. Mine also have Genisys only messages.
3. Uploaded post "Translated Genisys into Korean." in Korean mcpe community, after uploading that @ParkChanSol and me talked about translation
_Chat:
J as me, P as @ParkChanSol
P: Did you also translated genisys_kor.yml?
J: Nope, does it even able to translate it?
P: I translated genisys_kor.yml
J: Do you mean your post (His (Her) Korean translated Genisys)?
P: Nope, I haven't update it yet (Github pull request link: https://github.com/iTXTech/Genisys/pull/1837)
J: Oh, the user who did 3 pull request before me was you!
P: Yep, I was almost gonna get ban because of not enough information
J: (Sent about his (her) genisys_kor.yml invaild understand - I can also put it but I think it's waste of time)
P: Please modify it when it gets verified.
J: Ok.

So I added my own genisys_kor.yml, but sightly verified on that version. Me and @ParkChanSol knew each other today, it didn't meant to be collaborate!

So could you please merge this pull request? Thanks.

**Comment by ishitatsuyuki** [comment]
No, we don't like two merge requests. Since you guys have connection, please ask him to make you as collaborator.

This can cause serious merging conflict. You should resolve the conflicts on you guys' side.

**Comment by ParkChanSol** [comment]
@ishitatsuyuki We don't know each other

**Comment by ParkChanSol** [comment]
@ishitatsuyuki I don't understand your action(Korean is one of language, but you ignore Korean)
I want your answer

**Comment by ishitatsuyuki** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**You even thought that the same file can be merged from two?**

**Pull request closed without merging**
