### PR TITLE
Update EntityEffectRemoveEvent.php and EntityEffectAddEvent.php

### PR DESCRIPTION
**Pull request by sero583**
New getter, called EntityEffectRemoveEvent::getEffect(); and new setter and getter called EntityEffectAddEvent::getEffect() and EntityEffectAddEvent::setEffect(Effect $effect);

### CODE REVIEW

**Comment by dktapps** [comment]
Formatting is a mess, and you've used GitHub Web Editor. Please correct these issues and squash your commits. -1.

**Comment by sero583** [comment]
@dktapps Im very sorry for that, i'll just wanted to help. Anyways could you add those setters and getters to it?

**Comment by sero583** [comment]
PS: @dktapps I'm a GitHub noob, so... what is squashing?

**Comment by dktapps** [comment]
Read the contribution guidelines.

**Comment by ishitatsuyuki** [comment]
No activity. Closing.

**Pull request closed without merging**
