### PR TITLE
Can you make run for people who has win 7 and php 7 don't work for us

### PR DESCRIPTION
**Pull request by GrimDevs**
Can you like code a update for the people who has window 7 and there pic can't be upgraded to win 10 or 8 because there are not compatible to use it if you could code it I. PHP5 it could help us instead of go out beying new ones that have the same ram and cpu I mean I have me pic it off because me server it stuck on 0.13.2 and I shan't to play I thick that should get php 7 for win 7 I am on win 7 plz reply and let other also think ok

### CODE REVIEW

**Comment by gaoyichuan** [comment]
I can tell you that PHP7 Binary works for win7

**Comment by GrimDevs** [comment]
Ok then make the a zip of it for me then k can get it because it been hell for me try to find php7

**Comment by GrimDevs** [comment]
I had heel
 Try to find php 7

**Comment by gaoyichuan** [comment]
@GrimDevs See this
https://github.com/iTXTech/PHP-Genisys

**Pull request closed without merging**
