### PR TITLE
New Caves Populator

### PR DESCRIPTION
**Pull request by PeratX**
### Description

Implemented new CavesPopulator

### Reason to modify

The old one is not good

### CODE REVIEW

**Comment by ExerciseBook** [comment]
又一个pull。。。。 _(:з」∠)_ 
That is great _(:з」∠)_

**Comment by PeratX** [comment]
想表达什么？？？

**Comment by ExerciseBook** [comment]
很厉害的意思。。。

**Comment by PeratX** [comment]
欢迎大神（看了你的项目之后）2333

**Comment by ExerciseBook** [comment]
我不会php啊。。。

**Comment by PeratX** [comment]
你会pascal啊（被noip带进坑的？

**Comment by ExerciseBook** [comment]
是啊。。我肛noip的

**Comment by PeratX** [comment]
2333

**Comment by dktapps** [comment]
Oho, I have _got_ to test this

**Comment by ZedCee** [comment]
- The cave densities are rather high.  
- All lava pools are exactly the same y-axis at exactly one block of depth.  
- Looks more like overlapping a mass of smaller caves to achieve a "tunnel" effect.  
- Cannot dig basements; aka Don't dig down on Grass Blocks.

This is not does not look production level for regular land generation. :disappointed: 
Still prefer larger caves and generating tunnels using [Brightmoore's Underworld filter](https://sites.google.com/a/brightmoore.net/brightmoore/mcedit-filters-1/underworld) for [MCEdit](https://github.com/Khroki/MCEdit-Unified) which produces interesting caves that exceed MCPCs and overlap the present generation just fine.  For lava I just replace existing cave air below a certain level.

On a more positive note:  The bedrock generation is perfect. :+1:

**Comment by PeratX** [comment]
@ZedCee I have problems with overlap generate, can you take a look at it? ( the latest commit)

**Comment by ZedCee** [comment]
Taking a quick peek before bed, just generating some maps now

**Comment by ZedCee** [comment]
Wow.
Those biomes are looking nice.  The overlap is a little quirky, but looks way better.
In general more interesting to look at and to explore.  
The large differences in the elevation are very nice. 
The water is most notable, the rivers look great cutting through the biomes and large bodies of water interconnecting really adds to the generation.

Forgive a small island with cacti and a few dirt blocks covered in snow (funny actually), it's coming along nicely.

**Comment by PeratX** [comment]
@ZedCee Thanks.

**Comment by Muqsit** [comment]
Wow! Looks hawwt!!

**Comment by dktapps** [comment]
Did you leave an echo or var_dump in somewhere? This is just a small portion of what my terminal got spammed with when starting the server:
```
160, 4, 205 1
160, 3, 205 1
160, 2, 205 1
160, 4, 206 1
160, 3, 206 1
160, 2, 206 7
160, 4, 207 1
160, 3, 207 7
160, 2, 207 1
161, 4, 204 7
161, 3, 204 11
161, 2, 204 11
161, 4, 205 1
161, 3, 205 1
161, 2, 205 1
161, 4, 206 7
161, 3, 206 1
161, 2, 206 1
161, 3, 207 7
161, 2, 207 7
162, 3, 205 7
162, 2, 205 7
162, 3, 206 1
162, 2, 206 1
160, 4, 205 11
160, 3, 205 11
160, 2, 205 11
160, 5, 206 1
160, 4, 206 11
160, 3, 206 11
160, 2, 206 7
160, 5, 207 1
160, 4, 207 11
160, 3, 207 7
160, 2, 207 11
161, 4, 205 11
161, 3, 205 11
161, 2, 205 11
161, 4, 206 7
161, 3, 206 11
161, 2, 206 11
161, 4, 207 1
161, 3, 207 7
161, 2, 207 7
162, 3, 206 11
162, 3, 207 1
160, 5, 206 11
160, 4, 206 11
160, 3, 206 11
160, 5, 207 11
160, 4, 207 11
160, 3, 207 7
161, 4, 206 7
161, 3, 206 11
161, 5, 207 7
161, 4, 207 11
161, 3, 207 7
```

**Comment by dktapps** [comment]
Hmm. Testing this out and some of the terrain looks a little abnormal, like the below screenshot. But this is a HUGE, HUGE improvement over the current generator.

image

**Comment by ZedCee** [comment]
For posterity's sake:
2016-07-17 11-32-29-am
:laughing: 

I also saw the numbers, but I'm sure I've seen that in testing before...
Nevertheless I and a loyal tester are going to be generating more maps today.

**Comment by dktapps** [comment]
I _love_ the new caves, rivers, biome borders not looking like walls, etc., but I really don't like the patterning in the terrain in the new generation. It makes my nose itch. Stupid thing, but it's true.

**Comment by ZedCee** [comment]
@dktapps At foot level it's less noticeable.  I feel like some biomes could use a size increase and it may make that a little better, but I need to look further into it this aft.
Lots of large plains, some of that may look good as a ocean instead, that may also clean up some of the artifacts.

**Comment by ZedCee** [comment]
@PeratX Following up with some suggestions on biomes and overlap:
- Some biomes could be larger, such as taiga, maybe even the beaches, as well as oceans(which could be much deeper)
- Plains should be smaller (Perhaps if oceans and plains were inverse of each other)
- Beaches probably shouldn't have cacti (deserts less), and should appear a little more frequently (Although the above may fix the visual frequency)
- Somethings off with snowy plains (maybe its size, maybe its population related, less flowers and the occasional spruce wouldn't hurt)

I think some of the above could seriously change how the present overlap looks. There's a chance it could also improve coastal artifacts as well.  I understand some of its population related, they're just further notes that could improve the look.  On foot it looks decent.
I have other ideas, but I think its just more population stuff.
 +1eleventy

**Comment by TNT2000** [comment]
66666

**Comment by dktapps** [comment]
@TNT2000 Stop spamming.

**Comment by dschwartz783** [comment]
This is good news! Genisys-generated caves are somewhat underwhelming at the moment. Mostly large sometimes interconnected spheres...

**Comment by ZedCee** [comment]
**@PeratX Wow!
Yet another great improvement to the biome generation!**
I'm loving the variety of tree densities and sizes of some of these forests.  The way some follow along a river looks great.  
Still something off with the massive plains, it would be really nice to see some rivalling deserts and the occasional small residual grouping of trees on them; maybe I can find a seed with some artifacts that look like that.

I'll look it over more tonight and fill in a bit more if I come up with something.

**Comment by PeratX** [comment]
+1

**Comment by dktapps** [comment]
Plus: Overlap seems better.
Minus: No caves. Not a single one.
It seems the terrain abnormality is mainly near water bodies. But there seems to be a crippling issue with the newest build https://gitlab.com/itxtech/genisys/commit/ae5762dd9422a4c511c4c5e234b8dff1a3b61092
I haven't found a single cave. Flown around in spectator and haven't seen a thing in hundreds of chunks.

**Comment by ishitatsuyuki** [comment]
First: squash.
Second: have you fixed the issue above?
Code Review -1

**Comment by ZedCee** [comment]
Somewhere along the line I feel like this became biome and cave were temporarily turned off?  Correct me if I'm wrong.

**Comment by ZedCee** [comment]
Back to swiss cheese! :cheese:
Just see my first comment.

**Comment by PeratX** [comment]
@ZedCee That will improve later.

**Comment by dktapps** [comment]
Seriously stop with the force-merges. We have code review for a reason. >.<

**Pull request merged**
