### PR TITLE
Generator: Cactus and Sugar Cane rewrite

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Remove the problematic tall generators and merge it to one instead.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Please test and give a review. I'm setting the count to 10 instead of those excessive numbers, not sure if this will increase or decrease.

**Comment by gaoyichuan** [comment]
-1 for this:
 There are sugarcanes everywhere and they are all one block tall

**Comment by ishitatsuyuki** [comment]
I have rewritten the things. Please check again.

**Comment by ishitatsuyuki** [comment]
I have tested this and I personally think this is OK. Please cast a vote.

**Comment by gaoyichuan** [comment]
+1 for this

[Approved with PullApprove](https://pullapprove.com/iTXTech/Genisys/pull-request/1433/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=iTXTech/Genisys)

**Comment by dktapps** [comment]
-1. Reason: I generate a new world and this spams the terminal:
```

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71

Notice: Undefined variable: water in C:\Users\Admin\Downloads\Genisys\src\pocketmine\level\generator\populator\Sugarcane.php on line 71
```

**Comment by ishitatsuyuki** [comment]
@dktapps I have pushed a fix. Please try again.

**Comment by dktapps** [comment]
Okay. Tested this. My findings so far:

- [x] Oversized cacti/sugarcane seems fixed
- [x] Spawn positions are realistic now

Other observations:
- Sugarcane is less common (not necessarily a bad thing)
- Cacti are _much_ too common (see screenshot).

image

**Comment by ishitatsuyuki** [comment]
I felt cactus are generated like this much also in vanilla. I will reduce a bit of generation then.

**Comment by ishitatsuyuki** [comment]
This is the final commit by me. If you still want to change parameters, feel free to force push to this branch.

**Comment by dktapps** [comment]
image

**Comment by ishitatsuyuki** [comment]
Wait: give me the seed so I can do something about that.

**Comment by dktapps** [comment]
Seed: 1468319490
Trying to find the coordinates now, my server crashed

**Comment by dktapps** [comment]
Seems to have been a freak coincidence. Every other sugarcane I've found has been normal-sized. I'll give this a +1

**Comment by dktapps** [comment]
image

Coordinates (of myself): X=-749, Y=79, Z=-1496
Seed: 1468319490

**Comment by gaoyichuan** [comment]
+1 and merge

**Pull request merged**
