### PR TITLE
Minecraft 0.15.10 Support

### PR DESCRIPTION
**Pull request by TheAppleGamer**
### Description

It adds support for 0.15.10

### Reason to modify

You can't play on 0.15.10 without it
### Tests & Reviews

I have tested the code and it works

minecraft - pocket edition_20161004_234201

### CODE REVIEW

**Comment by NoHaxJustTryHqrd** [comment]
i also have tested the code and no game breaking changes were found

**Comment by MattWAnderson** [comment]
This does not work. New 15.10 clients join with underscore and get outdated client. ___[/179.34.88.*:19132] logged out due to Outdated client!

**Comment by TheAppleGamer** [comment]
@MattWAnderson It does work, I've had a bunch of people test it.

**Comment by ishitatsuyuki** [comment]
We need some details about protocol changes before just bumping the version.

**Comment by dktapps** [comment]
Tested joining != tested and 100% working. I've said this before: you don't bump version numbers for no reason.

**Comment by TheAppleGamer** [comment]
The version numbers get bumped here everytime the protocol changes though...

**Comment by dktapps** [comment]
@TheAppleGamer you don't get it. CURRENT_PROTOCOL is the protocol _version number_, not the actual protocol.

**Comment by dktapps** [comment]
This has been merged to a branch. It will be merged to master once we have verified that no further changes are required.

**Pull request closed without merging**
