### PR TITLE
Allow cancelling hunger healing

### PR DESCRIPTION
**Pull request by XFuryMCPE**
### Description

You can now cancel EntityRegainHealthEvent when the cause is by hunger

### Reason to modify

^^^^

### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by IrishUHC** [comment]
Good PR, I have no idea why it wasn't in there in the first place.

**Comment by dktapps** [comment]
Perhaps because of this? https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/entity/Living.php#L91

**Comment by dktapps** [comment]
Correction: _this_
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/entity/Entity.php#L703

**Comment by dktapps** [comment]
> - Have you made sure that there is actually a problem before trying to fix it?

Please learn, or I'm going to ban you again.

**Pull request closed without merging**
