### PR TITLE
Ton of 0.15.0 fixes

### PR DESCRIPTION
**Pull request by XFuryMCPE**
Fixed these bugs (0.15.0):
 - Blocks not updating
 - Lead attaching to all existing mobs on current world
 - Players not appearing to move

Other fixes:
 - Small bug when setting the server name in installer
 - Removed StrangePacket.php
 - Tiny spacing fix in a file lol

New:
 - Started on ClientToServerHandshakePacket
 - Started on ServerToClientHandshakePacket

### CODE REVIEW

**Comment by Muqsit** [comment]
ClassNotFoundException: "Class pocketmine\network\protocol\ClientToServerHandshakePacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by XFuryMCPE** [comment]
lol whoops now try

**Comment by AllMCPE** [comment]
How do I download it?

**Comment by dktapps** [comment]
The Handshake packets are unnecessary. Also you've made changes which will conflict with other PRs which are already open.

**Comment by daniktheboss** [comment]
Go to his account and download his code... I'll check it for more bugs right now

**Comment by AllMCPE** [comment]
I cant convert it to phar...

**Comment by daniktheboss** [comment]
You don't have to convert it to phar... delete the old phar file and put the src folder in the genisys FOLDER and run the start.cmd

**Comment by daniktheboss** [comment]
@xfurrymcpe I tested your build and it works great!! Found no bugs for now... multiworld works great with build!! Thanks a bunch

**Comment by ZizzyZizzy** [comment]
16.06 15:20:45 [Server] INFO Notice: Undefined variable: mini in phar:///home/multicraft/jar/pocketmine/genisys/Genisys.phar/src/pocketmine/level/Level.php on line 815

In this block:

        if(count($this->changedBlocks) > 0){
            if(count($this->players) > 0){
                foreach($this->changedBlocks as $index => $blocks){
                    foreach($mini as $blocks){
                        foreach($blocks as $b){
                            foreach ($this->getUsingChunk($b->x >> 4, $b->z >> 4) as $player) {
                                $pk = new UpdateBlockPacket();
                                $pk->records[] = [$b->x, $b->z, $b->y, $b->getId(), $b->getDamage(), UpdateBlockPacket::FLAG_ALL];
                                $player->dataPacket($pk);
                            }
                        }
                    }
                }
            }else{
                $this->chunkCache = [];
            }

**Comment by AllMCPE** [comment]
danik, now my pm wont work...

**Comment by AllMCPE** [comment]
Could u send me a vid on how to do it?!

**Comment by daniktheboss** [comment]
Found one bug... in spawn u can hit people but they don't take damage... but in rest of world they do...

**Comment by daniktheboss** [comment]
Are u using genisys folder?

**Comment by ZizzyZizzy** [comment]
With "mini" changed to "blocks", it spits out another warning:

16.06 15:37:07 [Server] INFO Notice: Trying to get property of non-object in phar:///home/multicraft/jar/pocketmine/genisys/Genisys.phar/src/pocketmine/level/Level.php on line 817

817:                             foreach ($this->getUsingChunk($b->x >> 4, $b->z >> 4) as $player) {

Still works though. Lava and water flow, mobs move and die when struck, experience orbs move.

**Comment by Gamecrafter** [comment]
@XFuryMCPE Why didn't you just do everything in one commit? It's very messy doing it this way. Plus, @ishitatsuyuki doesn't like it when you do it like this.

**Comment by AllMCPE** [comment]
danik, idk what u even mean by genisys folder...

**Comment by XFuryMCPE** [comment]
@Gamecrafter Copying and pasting my local code into the github editor

**Comment by Gamecrafter** [comment]
@XFuryMCPE What?! Just use git locally and push it from there. No need to get the GitHub editor involved.

**Comment by daniktheboss** [comment]
server logs- "Notice: Undefined variable: mini in C:\Users\Daniil\Desktop\Genisys\src\pocketmine\level\Level.php on line 815

Warning: Invalid argument supplied for foreach() in C:\Users\Daniil\Desktop\Genisys\src\pocketmine\level\Level.php on line 815".... no errors tho on client

**Comment by ishitatsuyuki** [comment]
I won't merge until you squash it. That's way too much history spam.

**Comment by gaoyichuan** [comment]
@ishitatsuyuki Just squash it using github.

**Comment by XFuryMCPE** [comment]
@ishitatsuyuki @gaoyichuan How... I never use Github and dk how

**Comment by ZizzyZizzy** [comment]
Spawn protection is not working. Natively or with plugins. Players can break any blocks they feel like.

**Comment by ImWalla** [comment]
It is, i just tested it on Fury's server. @ZizzyZizzy

**Comment by ZizzyZizzy** [comment]
Ahh, shoot, so it is. The deop command forces lower-case when trying to remove op, so it never de-opped me! I opped myself in console using copy and paste, which has upper-case chars. I'll open a separate bug report for this.

**Comment by daniktheboss** [comment]
@ZizzyZizzy i can confirm the spawn protection is working great... the only thing is that when players hit other players in spawn, the player getting hit it getting the red skin thingy like hes taking damage but he actually is not.

**Comment by XFuryMCPE** [comment]
@ZizzyZizzy that was the block update bug, which I fixed in this version

**Comment by ImWalla** [comment]
How can i get the phar or the src?

**Comment by daniktheboss** [comment]
screenshot_2016-06-16-17-00-08
bug... mob spawner when a mob is placed in... spawns nothing and there is a green line going around coming out of the head of the mob... pic explains better lol

**Comment by ishitatsuyuki** [comment]
You must use command line client to resolve conflict and squash commits.

**Comment by Adam1609** [comment]
Something problem with getAdditionalChar too.

**Comment by Driesboy** [comment]
the client crash after walk 5 blocks away from the spawn

**Comment by dktapps** [comment]
I'm having reports of crashes relating to undefined properties with these patches. Please fix this. Also you will need to rebase and squash your commits before this can be accepted.

**Comment by dktapps** [comment]
I'd like to say that it's a dangerous idea to copy and paste code. I've just fixed the block updates with a single line of code, whereas you copied and pasted a whole chunk of code in and it didn't work properly. Closing.

**Pull request closed without merging**
