### PR TITLE
Add absorption effects?

### PR DESCRIPTION
**Pull request by XFuryMCPE**
Should work, will get back once I test it

### CODE REVIEW

**Comment by Muqsit** [comment]
Good jab! +1

**Comment by XFuryMCPE** [comment]
It works? @Muqsit

**Comment by Muqsit** [comment]
@XFuryMCPE I am not certain of that but Absorption wasn't registered in Effects completely.

**Comment by dktapps** [comment]
Interesting. I'd prefer you test your code before making a PR though if possible, it saves all sorts of inconvenience.

**Comment by XFuryMCPE** [comment]
@dktapps True, sorry about that. I tested it and nothing happens so I guess it didn't work :P dunno why..

**Pull request closed without merging**
