### PR TITLE
MOB_EQUIPMENT_PACKET fix

### PR DESCRIPTION
**Pull request by svilex**
Now sending the right item to viewers.

### CODE REVIEW

**Comment by dktapps** [comment]
I don't have this problem. Have you tested this thoroughly?

**Comment by Driesboy** [comment]
i think it work the only change is replace a line!

**Comment by svilex** [comment]
-.- YES. The previous item is sent.


HOW TO REPRODUCE:

- Delete the "players" folder
-  Start the server
- Join the server with a friend and make sure you are in GameMode 0
- Your friend should be not too far from you
- Break a block and pick up the dropped item
- Your friend can't see your held item
- Left the game and join again
- Now your friend can see your held item

Follow all these steps to reproduce the bug.

**Comment by dktapps** [comment]
@svilex ah. In future I recommend you include your description in the PR message so that we understand what effects your changes have. Anyway, this looks good to me. Code Review +1.

**Comment by svilex** [comment]
@Driesboy Sure it is. But you can't judge by counting lines

**Comment by Muqsit** [comment]
+1

**Comment by Driesboy** [comment]
@svilex ok xD

**Pull request merged**
