### PR TITLE
Green "0.14.1" text in server list

### PR DESCRIPTION
**Pull request by AryToNeX**
It must be this way in my opinion; many players don't want to join my server because they think it is incompatible with 0.14.1

### CODE REVIEW

**Comment by Driesboy** [comment]
now 0.14.0 is red

**Comment by erkam2002** [comment]
use 0.14.1 :D

**Comment by markkrueg** [comment]
I tested these changes and it seems to cause problems for 14.0 players (they cannot connect). It keeps giving the "blocked for 5 seconds" thing. 

So I recommend not accepting this Pull until further testing can be made.

**Comment by gaoyichuan** [comment]
Already added by @PeratX

**Pull request closed without merging**
