### PR TITLE
Added CustomBlockData to skulls

### PR DESCRIPTION
**Pull request by jojoe77777**
Tested and works.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
What's the purpose of this change?

**Comment by jojoe77777** [comment]
> What's the purpose of this change?

I used it to store data in the skull (I stored a string)

**Comment by ishitatsuyuki** [comment]
Skulls haas no inventory. Looks bad to me.

Code Review -1

**Comment by ishitatsuyuki** [comment]
No reply. Closing.

**Comment by jojoe77777** [comment]
> Looks bad to me.

Sorry, what looks bad to you?

**Comment by ishitatsuyuki** [comment]
Unneeded.

**Comment by jojoe77777** [comment]
> Unneeded.

Well I need it for use in my plugin...

**Comment by ishitatsuyuki** [comment]
Well you should redesign your plugin.

**Pull request merged**
