### PR TITLE
Fix little bug..)

### PR DESCRIPTION
**Pull request by samalero**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code Review -1
This is intended.

[Rejected with PullApprove](https://pullapprove.com/iTXTech/Genisys/pull-request/1227/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=iTXTech/Genisys)

**Comment by samalero** [comment]
If you use the code without the patch, the reports of the entrance to the game / exit the game will not be deducted from the configuration ...

Excuse for machine translation ...

**Comment by PeratX** [comment]
No. Send message on log in and log out is using original pocketmine api

**Comment by PeratX** [comment]
No. Send message on log in and log out is using original pocketmine api

**Comment by samalero** [comment]
Just messages that are sent to the console, not formatted and sent to the same and players ...

**Pull request closed without merging**
