### PR TITLE
Update Info.php

### PR DESCRIPTION
**Pull request by RedstoneAlmeida**

### CODE REVIEW

**Comment by Muqsit** [comment]
woaah

**Comment by ishitatsuyuki** [comment]
Code review -1

**Comment by Driesboy** [comment]
No

**Comment by Driesboy** [comment]
If u will use 0.15.0 on your server use betatester
You cannot use 0.15.0 and 0.14.0 and 0.14.1 on the same server!

**Comment by erkam2002** [comment]
Work not

**Pull request closed without merging**
