### PR TITLE
Mob spawner rewrite

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Spawns multiple, checks block underneath.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code Review+1: tested locally

**Comment by ishitatsuyuki** [comment]
@Muqsit @PeratX @gaoyichuan Friendly ping, please take a look.

**Comment by PeratX** [comment]
Code Review+1

**Comment by Muqsit** [comment]
Thanks A LOT :D

**Pull request merged**
