### PR TITLE
Cyclic restart of the server autodetection of port

### PR DESCRIPTION
**Pull request by samalero**
for Windows ;-)

### CODE REVIEW

**Comment by dktapps** [comment]
It would be preferable if you made this optional like the Linux start script.

**Comment by samalero** [comment]
Well, today I will add ...

**Comment by dktapps** [comment]
Code Review -1. Reason: This script will crash the first time the server is run.

**Comment by dktapps** [comment]
No, this isn't the right way to do it. Now it starts lots and lots of server instances when the setup wizard is running.

**Pull request closed without merging**
