### PR TITLE
0.15 critical bug fixes - fixes most problems on the checklist in #1180

### PR DESCRIPTION
**Pull request by dktapps**
I've just spent the last two hours sifting through the code changes made in #1185, which was an absolute nightmare. Turns out most of the code was copy-pasted from Steadfast2 and was completely unnecessary. I've finally trimmed it down to the useful bits and fixed most of the issues on the checklist on #1180 .

Fixes:
- Mob spawns will no longer crash the game (thanks @Muqsit )
- Players are no longer tethered to all other mobs/players (thanks again to @Muqsit )
    
**EDIT**: Leash issues are _partially_ fixed.
- Mobs now move again (without walking round backwards!) (credits to Steadfast2 by way of @XFuryMCPE )
- Block updates work again (credits to me)

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Oh really? By the way, I recommend you to do `git commit --author "Name <e@mail.com>"`

**Comment by dktapps** [comment]
@ishitatsuyuki yep. Do you want me to squash the commits?

**Comment by dktapps** [comment]
And thanks for the tip, I'll do that in future.

**Comment by ishitatsuyuki** [comment]
This will be OK. I approve this.

**Comment by Adam1609** [comment]
Oh wait, before merging, please check the getAdditionChar problem, opening the server will crash

**Comment by isoz** [comment]
Just tried this now, it's still far from production ready, therefore should not be merged to main branch.
Things I noticed:
Lead is still attaching to my NPC
Players still see themselves breaking blocks but it's only local
At first I thought teleport signs were causing crashes but now I believe it's flowing water that causes the client to instantly crash as soon as you get close to it.
Lot's of login timeout spam in console

**Comment by ishitatsuyuki** [comment]
@isoz what you mentioned is not the problem of the request, thus it should be merged so some issues can be resolved.

**Comment by Adam1609** [comment]
Since removing getAdditionalChar, my server crash permantly

**Comment by ishitatsuyuki** [comment]
@Adam1609 Stop spamming: put it at the meta issue. You will be banned if you continue to violate the rules.

**Comment by ishitatsuyuki** [comment]
@iTXTech/trusted

**Comment by Driesboy** [comment]
@isoz do you use fnpc or slapper?

**Comment by isoz** [comment]
Yep fnpc has leads to it

**Comment by Driesboy** [comment]
the problem is fixed for slapper!

**Comment by Muqsit** [comment]
Yay +1

**Comment by Muqsit** [comment]
I approve this too ^-^

**Comment by Muqsit** [comment]
Finally, yay!

**Comment by dktapps** [comment]
@Muqsit PullApprove seems to be a bit dumb; it hasn't picked up that you're now able to perform code reviews. I imagine it will work for future PRs.

**Comment by dktapps** [comment]
Aargh. That was unintentional. I hate regex!

**Comment by dktapps** [comment]
Hmm. It seems I was wrong; this doesn't completely fix lead issues. However, it is progress.
It appears to happen when switching worlds.

**Comment by dktapps** [comment]
@Muqsit Try and approve it again now, it should work. I've synchronized teams with PullApp rove so it should work now.

**Comment by XFuryMCPE** [comment]
Fix for FNPC:

Make NPC.php extend Human, rather than Location. Then where the $pk->metadata is to spawn the bots, add this:

[self::DATA_LEAD_HOLDER => [self::DATA_TYPE_LONG, -1],
[self::DATA_LEAD => [self::DATA_TYPE_BYTE, 0]]

That fixes the bots so they don't have the lead AND fixes it to make them turn towards you.

For slapper:

In SlapperHuman.php, add this where the entity spawning is ($pk->metadata):

[self::DATA_LEAD_HOLDER => [self::DATA_TYPE_LONG, -1],
[self::DATA_LEAD => [self::DATA_TYPE_BYTE, 0]]

hope i helped

**Comment by Muqsit** [comment]
Thank you soo much @dktapps

**Comment by dktapps** [comment]
ugh accidental approve againnnn

**Comment by Driesboy** [comment]
add this lz

**Comment by ishitatsuyuki** [comment]
@Driesboy stop spamming. The discussion is only for code review.

**Comment by ishitatsuyuki** [comment]
@Muqsit please try to approve again (if you have tested the changes).

**Comment by gaoyichuan** [comment]
Approve this, merge to master

[Approved with PullApprove](https://pullapprove.com/iTXTech/Genisys/pull-request/1193/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=iTXTech/Genisys)

**Comment by Muqsit** [comment]
Approve test

**Pull request merged**
