### PR TITLE
fix bug ,resultitem will be droped when a creative player with full i…

### PR DESCRIPTION
**Pull request by Alcatraz-Du**
### Tests & Reviews

…nventory crafts items

### CODE REVIEW

**Comment by dktapps** [comment]
Seems okay, but please provide the required details in future. I'll let you off this time since it's a very small change. +1.

**Comment by ishitatsuyuki** [comment]
Isn't this the supposed behavior?

**Comment by dktapps** [comment]
@ishitatsuyuki no, try it in vanilla MCPE. It drops the excess regardless of gamemode.

**Comment by ishitatsuyuki** [comment]
Approved.

**Pull request merged**
