### PR TITLE
German language

### PR DESCRIPTION
**Pull request by erkam2002**
### Description

Added german language

### CODE REVIEW

**Comment by SleepSpace9** [comment]
👎  Sorry, but many spelling mistakes.

**Comment by erkam2002** [comment]
....??

**Comment by SleepSpace9** [comment]
Missing commas, wrong spelling, but mostly all nouns in lower case.

**Comment by SleepSpace9** [comment]
But it's a pity for your work, if you like I try to correct it and create a new PR.

**Comment by erkam2002** [comment]
ok

**Pull request closed without merging**
