### PR TITLE
Leads Fix

### PR DESCRIPTION
**Pull request by Muqsit**
@dktapps What'ya think?

eea

### CODE REVIEW

**Comment by dktapps** [comment]
Awesome, looks like you've nailed it. Great work. I'll need to test this myself naturally.

**Comment by XFuryMCPE** [comment]
Why did you rip $addChar off the steadfast repository lol there's no use for it if you're only supporting 0.15.0+

**Comment by dktapps** [comment]
@muqsit Tested and works perfectly as far as I can tell.

**Comment by dktapps** [comment]
I think @XFuryMCPE is right about addChar though.

**Comment by XFuryMCPE** [comment]
Check my pull @dktapps , I fixed all known bugs for 0.15 and started working on the new handshake packets

**Comment by markkrueg** [comment]
It seems like I had to add the following to the top of Player.php to make this work:

use pocketmine\network\protocol\SetEntityDataPacket;

**Comment by Muqsit** [comment]
@markkrueg Yes, I did forget that but leads should be fixed without using SetEntityDataPacket file.
@dktapps But i've defined addChar and it will work even if you remove additionalChar off Player.php. addChar is private. Check Steadfast2...

**Comment by AllMCPE** [comment]
@Muqsit how do I download it

**Comment by Muqsit** [comment]
https://github.com/Muqsit/Genisys/archive/master.zip

**Comment by ishitatsuyuki** [comment]
This looks awesome. Please make sure this is your original right?

**Comment by ishitatsuyuki** [comment]
If you're ready with the changes, please squash it.

**Comment by XFuryMCPE** [comment]
It only works with genisys mobs, not custom ones (Slapper and FNPC), I'm guessing those plugins need to be updated, or can you fix that?

**Comment by SleepSpace9** [comment]
I got Slapper also fixed by changing **SlapperHuman.php** in plugin source (adding DATA_LEAD...  to metadata):
```php
            $pk->metadata = [
                2 => [4, str_ireplace("{name}", $player->getName(), str_ireplace("{display_name}", $player->getDisplayName(), $player->hasPermission("slapper.seeId") ? $this->getDataProperty(2) . "\n" . \pocketmine\utils\TextFormat::GREEN . "Entity ID: " . $entityId : $this->getDataProperty(2)))],
                3 => [0, $this->getDataProperty(3)],
                15 => [0, 1],
				Player::DATA_LEAD_HOLDER => [self::DATA_TYPE_LONG, -1],
				Player::DATA_LEAD => [self::DATA_TYPE_BYTE, 0]
            ];
```
I also used the PR of @XFuryMCPE  (https://github.com/iTXTech/Genisys/pull/1185/commits/6c316d8ea60a6a8eb8a29e6305c8b311f94c3bb9)

**Comment by Muqsit** [comment]
@ishitatsuyuki I don't have the permission to merge pr's or approve them. Can you do it please, I'm ready :)

**Comment by GenisysFTW** [comment]
Please merge asap

**Comment by AllMCPE** [comment]
@Muqsit Idk how to make it update the thingy tho

**Comment by Driesboy** [comment]
https://github.com/PMPlugins/Slapper/issues

**Comment by lolcraftboy** [comment]
Can y see players move now ?????

**Comment by ishitatsuyuki** [comment]
@Muqsit please accept your invitation ASAP.
`Invitations are sent via email and can be accepted at https://github.com/iTXTech`

**Comment by legoboy0215** [comment]
I believe
`
self::DATA_LEAD_HOLDER => [self::DATA_TYPE_LONG, -1],
`
It should be 
`
DATA_TYPE_INT
`

**Comment by dktapps** [comment]
@legoboy0215 this code has been tested and works flawlessly. I don't see any reason to tamper with it.

**Comment by Muqsit** [comment]
@ishitatsuyuki I'll do or next time before making a PR. My last exam is on Sunday, that day I'll figure out how to use gitbash

**Comment by dktapps** [comment]
@Muqsit A lot of people are waiting for these fixes to be incorporated into Genisys, especially since you fixed the mob crash. I'm going to open a new PR shortly to selectively incorporate changes from #1185 (which is too messy and has too many issues), if you want I can incorporate your changes from here too and @mention you in the commit so you get credited?

**Comment by Muqsit** [comment]
@dktapps that would be amazing!

**Comment by dktapps** [comment]
@Muqsit I'll do that then

**Comment by dktapps** [comment]
Committed these changes to 0.15-bugfixes branch. Anyone who wants to test changes can download a  phar [here.](https://gitlab.com/itxtech/genisys/builds/1865342/artifacts/download) I'll make a PR to master once I can properly incorporate fixes from #1185

**Pull request closed without merging**
