### PR TITLE
Fixes entities with metadata causing crashes

### PR DESCRIPTION
**Pull request by jojoe77777**
TODO: Find out how to use modifiers...

### CODE REVIEW

**Comment by Muqsit** [comment]
+1 interesting

**Comment by gaoyichuan** [comment]
Is this still work in progress?

**Comment by funnycars** [comment]
It is an error if you do not add the Entity
use pocketmine\entity\Entity;

**Comment by jojoe77777** [comment]
> Is this still work in progress?

No, it works

**Comment by ishitatsuyuki** [comment]
Code Review +1

**Pull request merged**
