### PR TITLE
Fix Particle Ids

### PR DESCRIPTION
**Pull request by NoHaxJustTryHqrd**

### CODE REVIEW

**Comment by NoHaxJustTryHqrd** [comment]
This fixes the Particle Ids. Lol

**Comment by Muqsit** [comment]
Nice but squash you commits next time. +1

**Comment by ishitatsuyuki** [comment]
Do not simply use the web editor, use descriptive commit message, also you need citation for this.

**Comment by dktapps** [comment]
Copy-pasted and incorrect. Closing. These are currently under testing at pmmp/PocketMine-MP, changes have not yet been merged due to some uncertainty over naming (blame Mojang).

**Pull request closed without merging**
