### PR TITLE
fix irondoor php5

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by GalvinGao** [comment]
@PeratX Please check the code. I think @Driesboy is doing _good work_.

**Comment by Jelly9912** [comment]
@Driesboy this is from IM?

**Comment by GalvinGao** [comment]
May be because his #127 is copying from IM.

**Comment by Driesboy** [comment]
yes its from IM but i work good

**Comment by keithkfng** [comment]
But maybe it's not your work...

**Comment by GalvinGao** [comment]
@CrayonDing keep eyes on him.

**Pull request merged**
