### PR TITLE
Now, it works fine. 

### PR DESCRIPTION
**Pull request by xpyctum**
- New sound types.
- Now it does not work if there is a block on top. (Like PC)

### CODE REVIEW

**Comment by Syntaxious** [comment]
Is Enchantments working?

**Comment by xpyctum** [comment]
@Syntaxious Maybe..

**Comment by Syntaxious** [comment]
Can you test it for me? and can you provide a link with the phar please?

**Comment by xpyctum** [comment]
Read red box.

**Comment by Syntaxious** [comment]
Ahh, right.

**Comment by PocketKiller** [comment]
Thanks.

**Pull request merged**
