### PR TITLE
fix irondoor php7

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by xpyctum** [comment]
=_=
Why door2?

**Comment by BlackShadow1** [comment]
You know Door2 isn't in PHP7?

**Comment by Driesboy** [comment]
O yes haha
I forgot to make it compatible with php 5

Dries C
Op 22-jan.-2016 19:22 schreef "BlackShadow1" <notifications@github.com>:

**Comment by GalvinGao** [comment]
@PeratX Please check the code. I think @Driesboy is doing _good work_.

**Comment by PeratX** [comment]
Copy from imagicalmine, Close

**Comment by PeratX** [comment]
Why need Door2. What's the different between Door and Door2???

**Comment by PocketKiller** [comment]
like Wood and Wood2

**Comment by PeratX** [comment]
I understand. But what's the different between Door and Door2?

**Comment by Driesboy** [comment]
iron door is not a door that you can open with click

**Pull request closed without merging**
