### PR TITLE
Remove jenkins button

### PR DESCRIPTION
**Pull request by XFuryMCPE**
Jenkins was removed and the button was showing as a broken image square thingy

### CODE REVIEW

**Comment by dktapps** [comment]
It's just crashed, that's all.

**Comment by XFuryMCPE** [comment]
oh lol

**Comment by XFuryMCPE** [comment]
I thought jenkins was replaced with Gitlab?

**Comment by dktapps** [comment]
We got a new one. It's funded by donations.

**Comment by XFuryMCPE** [comment]
Ohh okay

**Comment by PeratX** [comment]
Jenkins server is down for maintenance. It will be online in one or two days.

**Pull request closed without merging**
