### PR TITLE
Russian genisys.yml

### PR DESCRIPTION
**Pull request by SuperPuperSteve**
### Description

Add Russian genisys.yml

### Reason to modify

Add Russian genisys.yml
### Tests & Reviews

I have tested the code and it works

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Closing according to contribution guidelines.

**Comment by SuperPuperSteve** [comment]
no way

**Comment by SuperPuperSteve** [comment]
why couldn't you just merge this commit?

**Comment by ishitatsuyuki** [comment]
This is GitHub, use git, or go away.

**Comment by SuperPuperSteve** [comment]
why I must use git if I can use web editor?

**Comment by ishitatsuyuki** [comment]
Good, read contribution guidelines again, I'm too lazy to copy them for you.

**Pull request closed without merging**
