### PR TITLE
Fix PlayerDropItemEvent cancelling (ATTEMPT 2)

### LINKED ISSUE #1961: PlayerDropItemEvent not working
**Issue description**
https://youtu.be/RhHb93dPuvA
Pls watch video, item will be lose when i cancalled PlayerDropItemEvent
`public function noDrop(PlayerDropItemEvent $event) { $event->setCancelled(); } `

**OS and versions**

Genisys: 5e4bfc0
PHP Version: 7.0.3
OS : Linux, linux
Game Verison: 0.15.x

Sorry my bad english

### PR DESCRIPTION
**Pull request by XFuryMCPE**
### Description

Fixes #1961

### Reason to modify

^

### Tests & Reviews

Haven't tested, sorry :c will start testing when I'm able to use my new device, but I think (and hope) this method works.

### CODE REVIEW

**Comment by dktapps** [comment]
Untested PRs are unwelcome. Do not expect us to treat such PRs favourably, they make more work for us. Do not do this again.

On a more positive note, this looks fine.

**Comment by XFuryMCPE** [comment]
Sorry 😛

**Comment by ishitatsuyuki** [comment]
heh, use git client and test your things. you got correct on this, but please use descriptive commit messages.

**Comment by inferboy** [comment]
Daddy Fury didn't test

**Comment by XFuryMCPE** [comment]
Why am I being called Daddy Fury..? Lmao.

**Comment by inferboy** [comment]
Because you are furious like a dad! Lmao *Daddy Fury confused* xD

**Comment by ishitatsuyuki** [comment]
Anybody want to test? @XFuryMCPE, if you can do it's the best.

**Comment by inferboy** [comment]
i can do it

**Comment by XFuryMCPE** [comment]
Soooooooo

**Comment by XFuryMCPE** [comment]
Any testers find that it works?

**Comment by inferboy** [comment]
*Daddy Fury curious* xD

**Comment by XFuryMCPE** [comment]
yoooooo, it was tested and works lol, lets add it to genisys now? xd

**Pull request merged**
