### PR TITLE
Standardise $this->server calls

### PR DESCRIPTION
**Pull request by Striker209**
### Description

I was chilling around when I saw that

### Tests & Reviews

Now all Server calls are linked to $this->server instead of sometimes $server!

### CODE REVIEW

**Comment by dktapps** [comment]
Looks fine. +1

**Comment by ishitatsuyuki** [comment]
Do you REALLY need this? PHP is a reference based language and `$this->server` and `$server` should be pointing to the same object.

**Comment by ZedCee** [comment]
Was this even tested?  Could this break or fix anything?

**Comment by ishitatsuyuki** [comment]
@ZedCee it doesn't break anything since it's just a local variable, but I think it also does nothing.

**Comment by ZedCee** [comment]
That was the rhetorical question :wink:

**Comment by Striker209** [comment]
I didn't know if I should have made pull request only with that modification but it's just for code clarity

**Comment by ishitatsuyuki** [comment]
Closing: this is unneeded, and doesn't make it better or worse.

**Pull request closed without merging**
