### PR TITLE
Update Chest.php

### PR DESCRIPTION
**Pull request by GAalexandres**
Fix chest destroy bug if you make sand fall on it.
Thanks to @aodzip

### CODE REVIEW

**Comment by RandomAltThingy** [comment]
I thought a chest was solid? It's a TileEntity and not an Entity and Tiles are solid so wouldn't it be solid.

**Comment by PEMapModder** [comment]
Tiles have nothing to do with solid.
See also: brewing stand, sign, daylight sensor

And Entity has no solid nor non solid.

**Comment by gaoyichuan** [comment]
I don't think chests can be solid.. closing

**Comment by PocketKiller** [comment]
@gaoyichuan Chest::isSolid() returned false.

**Comment by GAalexandres** [comment]
Try it yourself please.

**Comment by gaoyichuan** [comment]
@PocketKiller So you think we should merge this?

**Pull request closed without merging**
