### PR TITLE
Add ServerShutdownEvent

### PR DESCRIPTION
**Pull request by XFuryMCPE**
### Description

Allows you to do things before the server restarts, or cancel the shutdown

### Reason to modify

XFury wanted ServerShutdownEvent, so fury gets ServerShutdownEvent xD

### Tests & Reviews
This HAS been tested and works perfectly.

### CODE REVIEW

**Comment by MichaelM04** [comment]
Accept this awesomeness! XD

**Comment by dktapps** [comment]
Edited on GitHub? When will you learn.

**Comment by XFuryMCPE** [comment]
sec fam

**Comment by dktapps** [comment]
And DO NOT spam any PRs or you will be banned.

**Comment by XFuryMCPE** [comment]
Yes sir, posting one more that has all commits merged. @dktapps

**Comment by dktapps** [comment]
No. Learn to force push.

**Pull request closed without merging**
