### PR TITLE
IcePlains is now MESA biome

### PR DESCRIPTION
**Pull request by Muqsit**
because i dont know how to register a biome!

### CODE REVIEW

**Comment by Muqsit** [comment]
er
Preview! :)

**Comment by Muqsit** [comment]
pend

**Comment by Muqsit** [comment]
werwerwerwerwerw

**Comment by xpyctum** [comment]
no.

**Comment by Muqsit** [comment]
??

**Comment by PocketKiller** [comment]
look up the code and try to register one, also those are not Mesa color biomes... doesn't have 'blue'

**Pull request closed without merging**
