### PR TITLE
Almost new brewing system.

### PR DESCRIPTION
**Pull request by dog194**
Brewing system rewritten.

Bugs fixed:
- Fix Player get wrong thing after drinking potion.
- Fix missing LightLevel for BrewingStand.
- FIx a wrong Explode when put SPLASH_WaterBottle into Cauldron filled water.
- FIx GlassBottle duplicate problem.
- Fix a bug that GlassBottle cannot be filled with Still_Water
- Fix MaxStackSize for potion and SplashPotion.
- Fix a bug that Cauldron cannot preserve SPLASH_POTION
- Fix some progress bar problems.(Still have some bug)
- Fix a bug that SPLASH_POTION cannot be brewed.
- Fix a bug that consume too many ingredients.
- Bug fix for match and register BrewingRecipe

Additions:
- Add PlayerGlassBottleEvent for filling GlassBottle.
- Add Potion_list
- Add $ingredients

Rewritten brewing recipe:
The information is from the official wiki.

### CODE REVIEW

**Comment by dog194** [comment]
终于搞完了。亲们帮忙核对下。东西有点多。可能哪里有没注意的。Orz.
Finally done.

**Comment by dog194** [comment]
Close  #906

**Comment by Muqsit** [comment]
+1

**Comment by ishitatsuyuki** [comment]
Please wait. I will do a rebase later.

**Comment by ishitatsuyuki** [comment]
GPLv3 requires to indicate sources. Are you OK with that?

**Comment by ishitatsuyuki** [comment]
Rebased. This looks good to me!

**Comment by dog194** [comment]
+1

**Pull request merged**
