### PR TITLE
Fix #1235

### LINKED ISSUE #1235: Hurt animation even though even is cancelled
#### Issue description
Title says it all.
#### Steps to reproduce the issue
Eh... Hit someone in spawn when you are using a plugin like PeacefulSpawn.
#### OS and versions
* Genisys: This server is running Genisys 1.2dev-919a195 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)
* PHP: 7.0.2
* OS: Linux Ubuntu

#### Crashdump, backtrace or other files
```
None
```
I really don't know the issue, but I see a patch 
[here](https://github.com/Hydreon/Steadfast2/commit/ccbf5c888e974dc2fa3084e6d3bfe88b1bcc6b29)

PS: In addition, there is this annoying death bug that happens to my server all the time, and another patch on Steadfast2 PROBABLY fixes it. The first issue is much more important though.
https://github.com/Hydreon/Steadfast2/commit/408baca649961a9be958cbe5926a87d29798c5c4

### PR DESCRIPTION
**Pull request by Muqsit**
Fix damage animation sent to client even after event gets cancelled!
Thanks to @tigerza117

### CODE REVIEW

**Comment by Muqsit** [comment]
+1?

**Comment by dktapps** [comment]
@Muqsit Code Review on your own PRs will be ignored xD

**Comment by dktapps** [comment]
I'll test this in a minute

**Comment by Driesboy** [comment]
it work!

**Comment by xxFlare** [comment]
@Muqsit Can you give credit to Steadfast...

**Comment by Driesboy** [comment]
work

**Comment by Muqsit** [comment]
@xxFlare given :) it's not steadfast btw

**Comment by Muqsit** [comment]
**NOTE:** This won't cancel damage animation when an entity falls from a height in a protected region.

**Comment by dktapps** [comment]
This seems fine. Code Review +1

**Comment by PeratX** [comment]
Nice work! +1

**Pull request merged**
