### PR TITLE
Added the french language

### PR DESCRIPTION
**Pull request by FaanMaario**
I wanted to help as I can :)

(I don't know if translate console messages is useful, so tell me if I should)

### CODE REVIEW

**Comment by dog194** [comment]
+1

**Comment by FaanMaario** [comment]
I'm happy that you like it :)

**Comment by Muqsit** [comment]
+1

**Comment by Muqsit** [comment]
Approved!

**Comment by Muqsit** [comment]
Code Review +1

**Comment by ishitatsuyuki** [comment]
Squash your commits.

**Comment by ishitatsuyuki** [comment]
There is still two.

**Comment by FaanMaario** [comment]
What did you say ishitatsuyuki ?

**Comment by ishitatsuyuki** [comment]
Squash your commits you can't understand?

Use the following great site to learn about it:
google.com

**Comment by FaanMaario** [comment]
I'm french so I can't understand all.
"Squash your commits" I understand but why ?

**Comment by FaanMaario** [comment]
I don't know how to do this sadly, I'm not used to use some options in Github . :/

**Comment by dog194** [comment]
@FaanMaario  He means that you should put all this change in one commit instead of two.

**Comment by ishitatsuyuki** [comment]
USE THE FOLLOWING GREAT SITE TO LEARN ABOUT SQUASHING:
google.com

**Comment by FaanMaario** [comment]
@dog194  Yeah but I'm not an expert, and @ishitatsuyuki I have ALREADY learn about squashing, I tried GIT and more and I can't do this.

**Comment by ishitatsuyuki** [comment]
So you are too stupid to pass our code standards. Code Review -1

**Comment by FaanMaario** [comment]
@ishitatsuyuki I just wanted to help; and I guess I'm TOO stupid to help like you said. Thanks.

**Pull request closed without merging**
