### PR TITLE
Refactor block internal API

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Probably fixes fire spreading

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Not tested: please take a look.

**Comment by Muqsit** [comment]
I can't say that the code doesn't do anything because it seems like im the only one facing a no-fire-spread-feature problem :3

**Comment by ishitatsuyuki** [comment]
Can you test if this doesn't crash and works as intended? Thanks for the help.

**Comment by Muqsit** [comment]
It doesn't cause any crashes but fire-spread never worked for me so I can't judge :/

**Comment by ishitatsuyuki** [comment]
@PeratX @CrayonDing @gaoyichuan friendly ping, please take a look.

**Comment by jellyfishcoder** [comment]
@Muqsit > I can't say that the code doesn't do anything because it seems like im the only one facing a no-fire-spread-feature problem :3
You are not alone, same for me. I just wanted to see what would happen if it was turned on, but it didnt work. I wont use it that much though, cause grievers.

**Pull request merged**
