### PR TITLE
Update Tile.php

### PR DESCRIPTION
**Pull request by astersx**
This will return false if getBlock() is null, so the server wont crash!!! 
So if you think that will fix the crash if by any chance getBlock() is null,  im happy i helped....
If im wrong please no insults 😝.

### CODE REVIEW

**Comment by astersx** [comment]
This is line 151 wich is false. return $this->level->getBlock($this);
if i check $this->lever->getBlock($this) is null?
if yes all function to be false if yes continue normal code.

im not soo good in php but i created a online php game in 1 week just with if and else :).
And database was similar with pocketmine (players folder). 
Anyway if this code fail,  i will try in another way to fix this.(im already using it on my sv)

**Comment by PeratX** [comment]
@astersx Does your server has Trapped Chests?

**Comment by astersx** [comment]
I put a trapped chest down from creative, changed to survival break it and took it!!!  Is like normal chest, so why u ask me.

**Comment by PeratX** [comment]
Because I think maybe something wrong with the Trapped Chest...

**Comment by astersx** [comment]
Ya,  but i edit pocketmine i use with code i comitted,  sooo :D.
Anyway until now no crashes so im good.

**Comment by PeratX** [comment]
@astersx We will test it later. Thx for your report!

**Pull request closed without merging**
