### PR TITLE
spawners drop spawner

### PR DESCRIPTION
**Pull request by daniktheboss**
### Description

Make the monster spawner drop spawner.

### Reason to modify
um, to make it drop the spawner

### Tests & Reviews
tested and will drop with pickaxe, hand, explotion

### CODE REVIEW

**Comment by Muqsit** [comment]
Looks like you haven't played vanilla survival much? eh??

**Comment by daniktheboss** [comment]
Lol not really... I guess it doesn't drop 😂

**Comment by KairusDarkSeeker** [comment]
Wow what a sore loser

**Comment by andris155** [comment]
Write a plugin this function.

**Comment by daniktheboss** [comment]
@kairusdarkseeker wtf? Just because I only play factions and don't remember stuff from vanilla means I'm a looser? FUCK YOU!

**Comment by dktapps** [comment]
That's enough thanks. Take your arguments elsewhere.

**Pull request closed without merging**
