### PR TITLE
Add XBOX check function (new API)

### PR DESCRIPTION
**Pull request by FaigerSYS**
### Reason to modify

 
I think there must be some API for XBOX :)

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Please don't save the useless pubkey. It's only for encryption handshake.

Also, please make a specific reason to get if a user is authenticated. Since the PC edition doesn't has such a function, I didn't add it too.

**Comment by FaigerSYS** [comment]
I want to make useful for some plugins. I have some ideas how to use this ability

**Comment by ishitatsuyuki** [comment]
Then describe. Your idea is too abstract.

**Comment by FaigerSYS** [comment]
It can be useful*

**Comment by FaigerSYS** [comment]
Fot example I want to use it in my auth plugin

**Comment by ishitatsuyuki** [comment]
There is already online-mode. More examples?

**Comment by dktapps** [comment]
This is redundant,  since either all players _are_ authenticated, or all players are not.

**Comment by dktapps** [comment]
It's pointless making per-player auth checks because it either applies to all players or none of them. A better approach is just to get the online-mode config from the server properties.

**Pull request closed without merging**
