### PR TITLE
Update Human.php

### PR DESCRIPTION
**Pull request by tigerza117**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code review +1

**Comment by dog194** [comment]
0.0 i think this is unnecessary. Human–>Creature->living. and in living $EnchantL is already set. So -1

**Comment by dktapps** [comment]
@ishitatsuyuki you really need to fix that

**Comment by dktapps** [comment]
whoops meant to click comment

**Comment by Driesboy** [comment]
my game crash after login for the 2e time

**Comment by PeratX** [comment]
This is unnecessary

**Pull request closed without merging**
