### PR TITLE
[WIP] Add German language

### PR DESCRIPTION
**Pull request by erkam2002**
Added German language 1/2

### CODE REVIEW

**Comment by dog194** [comment]
+1

**Comment by ishitatsuyuki** [comment]
Squash your commits, complete your work or add WIP in title.

**Comment by Goodstuff4UonYT** [comment]
*standard

**Comment by Goodstuff4UonYT** [comment]
This german is a really bad one :D

**Comment by dktapps** [comment]
@Goodstuff4UonYT In what way?

**Comment by Goodstuff4UonYT** [comment]
@dktapps I'm from Germany and this german is so bad as my english ^^
no case sensitivity...
misspellings...
and the translations are often not right.

**Comment by dktapps** [comment]
@Goodstuff4UonYT I may as well close this PR then xD

**Pull request closed without merging**
