### PR TITLE
Dog194 enchantment

### PR DESCRIPTION
**Pull request by dog194**
### Description

Enchantment
 - Sharpness, Smite and Bane of Arthropods
 - Fire Aspect, KnockBack and Looting.

### Reason to modify

Bring some work to your CPU.

### Tests & Reviews

Tested

### CODE REVIEW

**Comment by dktapps** [comment]
Travis CI failed on that last commit:
```
Fatal error: Cannot use pocketmine\item\Item as Item because the name is already in use in /home/travis/build/iTXTech/Genisys/src/pocketmine/entity/IronGolem.php on line 26
```

**Comment by PeratX** [comment]
+1

[Approved with PullApprove](https://pullapprove.com/iTXTech/Genisys/pull-request/1458/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=iTXTech/Genisys)

**Comment by ExerciseBook** [comment]
这里是第一个pull吗？

**Comment by ishitatsuyuki** [comment]
Code Review +1

**Pull request merged**
