### PR TITLE
Fix #889 again

### LINKED ISSUE #889: Enchanting consume too much Player's exp
#### Issue description

Enchanting consume too much Player's exp
#### Steps to reproduce the issue

Enchant on EnchantmentTable.
Login out
Login in
#### OS and versions

* Genisys:340?
* PHP:7
* OS:win

#### Crashdump, backtrace or other files
```
Paste here
```

### PR DESCRIPTION
**Pull request by dog194**

### CODE REVIEW

**Comment by dog194** [comment]
+ 1

**Comment by CrayonDing** [comment]
+1.

**Comment by dog194** [comment]
+1

**Comment by Muqsit** [comment]
+1 Am I late?

**Comment by ishitatsuyuki** [comment]
Just announcing: you can use the following expression to approve.

This works!

**Comment by ishitatsuyuki** [comment]
I'm just doing test here: never mind.
Approved.

**Comment by ishitatsuyuki** [comment]
Another test:
This doesn't work.

**Comment by ishitatsuyuki** [comment]
and one more:
This works

**Comment by ishitatsuyuki** [comment]
last one:
Well, it's working!

**Pull request merged**
