### PR TITLE
Add BossEventPacket

### PR DESCRIPTION
**Pull request by XFuryMCPE**
### Description

Adds BossEventPacket, which will allow us to create boss nametags at the top of the screen

### Reason to modify

read above

### Tests & Reviews

I have not tested this code lmao, stole it from Elywing but they tested it and it works fine.

### CODE REVIEW

**Comment by Muqsit** [comment]
you know you're gonna get rejected because of two things.

**Comment by Infernus102** [comment]
Lol

**Comment by XFuryMCPE** [comment]
lol i tried

**Comment by XFuryMCPE** [comment]
Welp.

**Comment by Infernus102** [comment]
Daddy Fury sad

**Pull request closed without merging**
