### PR TITLE
Create pardon aliases

### PR DESCRIPTION
**Pull request by ABAxStorm**
### Description

This adds aliases to the pardon commands for players who want to use /unban

### Reason to modify

Makes it easier to pardon people

### CODE REVIEW

**Comment by dktapps** [comment]
Code Review -1. You forgot some very basic syntax. Please correct this.

**Comment by dktapps** [comment]
This clearly wasn't tested before you opened the PR, or you'd have picked up on that.

**Comment by dktapps** [comment]
And do not consider PR-spamming either.

**Comment by ABAxStorm** [comment]
Correcting, found what I missed

**Comment by robske110** [comment]
please squash your commits

**Comment by dktapps** [comment]
Better. Please also squash your commits.

**Comment by robske110** [comment]
lol

**Comment by ABAxStorm** [comment]
Not sure I can squash.

**Comment by Yoyu666** [comment]
what is this do?

**Comment by dktapps** [comment]
@Muqsit it's WIP until he squashes his commits.

**Comment by dktapps** [comment]
I just noticed how it is you're actually doing this. You commit code on GitHub with the web editor, make a PR to yourself, and then squash-merge your own PR. That's frankly the stupidest way I've heard of to go about squashing. Did you read the contribution guidelines? DON'T USE GITHUB WEB. Closing.

**Pull request closed without merging**
