### PR TITLE
0.16 packets IDs

### PR DESCRIPTION
**Pull request by svilex**
I don't think a description is needed for this

### CODE REVIEW

**Comment by dktapps** [comment]
Mojang, you failures. Shift the whole list for one packet. 😂 Thanks very much.

**Comment by SleepSpace9** [comment]
Now I understand why my Nemisys freezes since today after a short while. I guess it happens when a player with 0.16 joins Nemisys. No error output but the java process of Nemisys takes over 100% of CPU and nothing happens after that, no disconnect, but also no other processing. I don't have 0.16, so I can't test, but I'm convinced Nemisys will also need an update.

**Comment by mhsjlw** [comment]
Protocol is version 90

**Comment by daniktheboss** [comment]
Where do u get these packet from?

**Comment by ishitatsuyuki** [comment]
@daniktheboss read the description, please don't spam on technical discussion.

**Pull request merged**
