### PR TITLE
Fix furnace recipes.

### PR DESCRIPTION
**Pull request by dog194**
### Description

Any kind of wood can be smelt to charcoal now.

### Reason to modify

The furnace recipes are sent incorrectly.

### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by dktapps** [comment]
If only NULL _did_ work the way it was supposed to. But this looks fine to me. Code Review +1.

**Comment by ishitatsuyuki** [comment]
Code review +1

**Comment by dktapps** [comment]
Tested this and can't find fault with it. Code Review +1.

**Comment by ishitatsuyuki** [comment]
Code Review +1 again: thanks for removing the redundant glass one.

**Pull request merged**
