### PR TITLE
0.15 Some Fixes

### PR DESCRIPTION
**Pull request by Muqsit**
- Fixed Leads on Players
- Temporarily removed additionalChar to avoid console spam

### CODE REVIEW

**Comment by dktapps** [comment]
I think `$additionalChar` and `getAdditionalChar()` can be safely removed. It is unused and PM doesn't have it anymore.

**Comment by Muqsit** [comment]
But Steadfast2 uses it...maybe it is used somewhere..

**Comment by dktapps** [comment]
I've searched the entire repo and there is no reference to it anywhere.

**Comment by dktapps** [comment]
Uhm... leashes
image

**Comment by Dog2puppy** [comment]
I think it looks good.

**Comment by daniktheboss** [comment]
Did u fix it?

**Comment by Muqsit** [comment]
@dktapps It happens with mobs but not with players.

**Comment by dktapps** [comment]
I'm sorry to say it _does_ still affect players, I've tested it

**Comment by Muqsit** [comment]
werw
There might be something else that the leashes get attracted to.

**Comment by Muqsit** [comment]
Fine, whatever. I'll fix all at once.

**Pull request closed without merging**
