### PR TITLE
Minor english lang fix

### PR DESCRIPTION
**Pull request by ABAxStorm**
Minor English language fix

### CODE REVIEW

**Comment by ABAxStorm** [comment]
Don't ask me why I did this lol

**Comment by ishitatsuyuki** [comment]
Code review +1

[Approved with PullApprove](https://pullapprove.com/iTXTech/Genisys/pull-request/1162/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=iTXTech/Genisys)

**Comment by dktapps** [comment]
Looks good to me. +1

**Comment by ABAxStorm** [comment]
@isoz lol

**Pull request merged**
