### PR TITLE
Use Online API if there is no OpenSSL extension

### PR DESCRIPTION
**Pull request by MrGenga**
### Description

Very useful thing, if you haven't updated php binaries, and you want XBOX auth, and if you have good internet connection, you can use that!

### Reason to modify

I think it is the best way, because it is crossplatform. If I used /usr/bi /openssl, there is no Windows support.
### Tests & Reviews

I have tested the code and it works. 

I think to move API to more stable server, then I create new pull request, with url change.

### CODE REVIEW

**Comment by minecrafter** [comment]
This sounds extremely scary, sending encrypted data and getting it back over an unencrypted connection, plus it's a remote server that I can't trust.

I would not recommend merging this PR.

**Comment by minecrafter** [comment]
#1703 is a much better solution (using the native PHP 7 `random_bytes()` function).

**Comment by gaoyichuan** [comment]
DO NOT use spaces, use TABs for your lines

**Comment by ZedCee** [comment]
@gaoyichuan That comes from using GitHub editor, hence why it is so strongly recommended against. ;)

**Pull request closed without merging**
