### PR TITLE
Fix lag with players on a bad network.

### PR DESCRIPTION
**Pull request by Muqsit**
Thanks to @Hydreon, hope this fixes 'lagg spikes'?

### CODE REVIEW

**Comment by Driesboy** [comment]
nice i test it now

**Comment by Driesboy** [comment]
work merge!

**Comment by Driesboy** [comment]
https://github.com/Hydreon/Steadfast2/commit/aca0cb3ab4cb19713b817b9c68685aa02bdce9ca

**Comment by dktapps** [comment]
Interesting. I can't verify that this solves the issue myself as I don't suffer from it, but looks good

**Comment by FaanMaario** [comment]
Just tested, it's amazing ! Works perfectly !

**Comment by dktapps** [comment]
Well by popular consensus that this resolves the problem, I'll give this a +1

**Pull request merged**
