### PR TITLE
0.15.4 Protocol Fix

### PR DESCRIPTION
**Pull request by TheAppleGamer**
### Description

Part one of 0.15.4

### Reason to modify

Players can join

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
We don't need such a PR unless you're sure everything else is also working correctly. Have you tested this?

**Comment by TheAppleGamer** [comment]
I've tested it and it works for MCPE 0.15.0 - 0.15.4

**Comment by ishitatsuyuki** [comment]
Do not use GitHub only to edit files. Please squash the commits.

**Comment by TheAppleGamer** [comment]
Don't know github that well so didn't understand that one bit, and that's all that is needed for 0.15.4

**Pull request closed without merging**
