### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
### Description

This commit changes following stuffs: Add string for enchant max level
update, some stuff change for Korean

### Reason to modify

Because there's new enchant max level range update, so I opened this pull request. Also, this edits some Korean stuffs better than previous version.

### Tests & Reviews

I have tested the code with latest version of Genisys from GitHub (Source code version), and I couldn't find any special issues.

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 제가 새로 만든 Pull Request 확인 좀 부탁드립니다. (참고로 님께서 마지막으로 만든 한국어 일부 수정에서 만들어진 모든 변경을 가져오지는 않았습니다.)

**Comment by iPocket** [comment]
Only edit kor.ini
Don't edit genisys.yml and remove the important -...

**Comment by KingDman** [comment]
@iPocket lets Collab Boi Plz

**Comment by Johnmacrocraft** [comment]
@iPocket Ok, from now I won't edit them unless there's new setting to translate. (The reason why I changed is there was useless line at end of file)
(Sorry for asking question, but I think nobody can answer) So, do I need to do something to get merged?

**Comment by Johnmacrocraft** [comment]
@iPocket Ok, from now I won't edit them unless there's new setting to translate. (The reason why I changed is there was useless line at end of file)
(Sorry for asking question, but I think nobody can answer to this) So, do I need to do something to get merged?

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 참고: 제가 이 Pull Request에서 수정해야 하는데 못 보고 지나친 부분이 있습니다. 그 부분들은 이 Pull Request가 Merge되면 올릴테니, 이후로 저보다 먼저 새로운 Pull Request를 만들게 되신다면 그 버전을 다운로드 해서 수정해 주시면 감사하겠습니다.

**Comment by ParkChanSol** [comment]
@Johnmacrocraft 님의 Korean Translation 브랜치에서 수정하시면 자동으로 PR에 올라갑니다

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 그건 그런데, 문제는 그렇게 되면 Commit이 2개가 되서 Genisys 관리자 분들이 "스쿼싱 (Squashing) 해주세요"라고 말하지 않나요? (Commit 합치는 방법을 모르는 1인)

**Comment by ParkChanSol** [comment]
@Johnmacrocraft 괜찮을걸요.

**Comment by Johnmacrocraft** [comment]
@ParkChanSol Done

**Comment by ParkChanSol** [comment]
@iPocket Why @Johnmacrocraft mustn't commit genisys_kor.yml?

**Comment by iPocket** [comment]
@ParkChanSol -_-
THE `-` WAS REMOVED. IT'S IMPORTANT.

**Comment by Johnmacrocraft** [comment]
@iPocket Emm... Is that joke or something? I don't think you're beginner at GitHub...

**Comment by Johnmacrocraft** [comment]
@iPocket Emm... Is that joke or something? I don't think you're beginner at GitHub... (If you didn't know (I hope it doesn't be true), - means I removed the specified line, and + means I added the specified line.
Example:
-hi
+hello
(That example means I deleted a line (hi), and I added a line (hello).)

**Comment by Johnmacrocraft** [comment]
@iPocket Emm... Is that joke or something? I don't think you're beginner at GitHub... (If you're beginner at GitHub (I hope this isn't true), **-** means that line got removed, and **+** means that line got added.)
Example:
-hi
+hello
(That example means I removed a line (hi), and I added a line (hello).)
If you're not beginner at GitHub and knows what **-** does so I'm wrong with this comment, what's the problem instead of saying - got removed?

**Comment by iPocket** [comment]
Nothing's changed.
Weird.

**Comment by ParkChanSol** [comment]
@iPocket Thanks to merged

**Pull request merged**
