### PR TITLE
[WIP][DO NOT MERGE]0.14.2 updates

### LINKED ISSUE #869: 0.14.2 update
Assuming you're already working on it. Need an urgent update to support 0.14.2.

Thanks!

### PR DESCRIPTION
**Pull request by Muqsit**
This will close #869

### CODE REVIEW

**Comment by Muqsit** [comment]
+1 I tested it

**Comment by ishitatsuyuki** [comment]
I thought 60 was 0.15...
Rejected: holding for now.

**Comment by Driesboy** [comment]
60 is 0.15.0 see my big brother project

**Comment by Driesboy** [comment]
i am sure it work!

**Comment by Driesboy** [comment]
i have tested

**Comment by ishitatsuyuki** [comment]
Are you sure it's 60? If it's the same to 0.15, it should be the same protocol as 0.15.

I will be happy if you test local multiplayer with 0.14.2/0.15.0.

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
60 is protocol from 0.15.0 b1

**Comment by ishitatsuyuki** [comment]
@Muqsit learn to use git next time.
@Driesboy is it compitable? I have heard 0.15 changed a lot.

**Comment by Driesboy** [comment]
check it yourself on gamecraftpe.tk port 191328
sorry for advertising i will remove after test

**Comment by Driesboy** [comment]
i am updating it now

**Comment by Muqsit** [comment]
@ishitatsuyuki Alright.
Also don't merge the PR please. There is a really huge bug!!

**Comment by Muqsit** [comment]
Players can't mine, dig, place blocks, open chests etc.

**Comment by Driesboy** [comment]
what!

**Comment by ishitatsuyuki** [comment]
I knew that. There must be protocol changes. Anyone know about 0.15.0 situation?

**Comment by Driesboy** [comment]
i am working on 0.15.0
i make zip from apk from the update ok???

**Comment by ishitatsuyuki** [comment]
Bad English. I can't understand.

**Comment by Driesboy** [comment]
i will upload a zip format from the update ok?

**Comment by Muqsit** [comment]
OMG, ImagicalMine have pushed a similar commit to their public repo and they are having the same bug. They haven't updated their protocols too! That's...dumb :3

**Comment by Driesboy** [comment]
haha!

**Comment by Driesboy** [comment]
IM prank

**Comment by Driesboy** [comment]
i will list the bugs soon

**Comment by ishitatsuyuki** [comment]
Yeah, code review is important... Although @PeratX frequently does force merges.

**Comment by Driesboy** [comment]
i have mail mojang for protocol changes 
if i will have reply i will post it

**Comment by Driesboy** [comment]
Re: 0.14.2 protocols

Mojang  |  Apr 27, 2016 01:38PM CEST
This is an automatic reply to let you know that we have received your support request, do not respond to this email. We will get back to you as soon as possible, and there is no need to submit another ticket. To learn about our current response time visit our help article When will I hear back?

Thank you for your patience,
Mojang Customer Support

This message was sent to gamecraftpe@mail.com in reference to Case #1348896.

**Comment by Driesboy** [comment]
bugs: 
- you cannot place blocks
- you cannot break blocks
- you cannot open chests or furnaces

**Comment by GrownPHP** [comment]
When there will be a Genisys version for 0.14.2??

**Comment by ishitatsuyuki** [comment]
@GrownPHP If you don't want to be taken as idiot, don't ask for ETAs.

**Comment by GrownPHP** [comment]
Sorry, that I asked..

**Comment by jellyfishcoder** [comment]
@GrownPHP It varies a lot, I blame it on Mojang for not publicly posting protocol changes

**Comment by Driesboy** [comment]
i dont have get answers from mojang

**Comment by Muqsit** [comment]
Maybe they wanna limit things so that players switch to realms instead?

**Comment by Driesboy** [comment]
I think no 0.15.0 release date: end july

**Comment by jellyfishcoder** [comment]
I hope not

**Comment by Driesboy** [comment]
0.15.0 protocols https://confluence.yawk.at/plugins/servlet/mobile#content/view/1998873

**Comment by gaoyichuan** [comment]
Hold for some days

**Comment by NiclasOlofsson** [comment]
Guys, you need to check the additions to adventure settings packet.

**Comment by Pub4Game** [comment]
Heh, I think this will help you https://github.com/Nukkit/Nukkit/commit/8f18813820c241190f3ba18d54dc1119cb89303d

**Comment by CLiu13** [comment]
See this: https://github.com/PocketMine/PocketMine-MP/commit/ac482621a108bfde0919e58d5aced382a760e719

**Pull request closed without merging**
