### PR TITLE
Extend API even more!

### PR DESCRIPTION
**Pull request by Muqsit**
This will allow players to code custom enchantment plugins and etc. (P.S I am coding one and this is an essential). I won't be merging tho, players have different preferences! :/

### CODE REVIEW

**Comment by dog194** [comment]
I think you solve your problem in a wrong way. If your plugin want to add something. You should change   /src\pocketmine\item\enchantment

**Comment by dog194** [comment]
This is to make sure player do not input the wrong param. and to aviod some other problem. So -1

**Comment by Muqsit** [comment]
@dog194 If you know how to change it through a plugin, please let me know :3

**Comment by dog194** [comment]
@Muqsit 0.0 I dont know. Maybe you need to ask others.

**Comment by gaoyichuan** [comment]
Maybe we need an API for managing custom enchantments .

**Pull request closed without merging**
