### PR TITLE
New API for exp calculation. Fix #1930 and remove lots of stupidity.

### LINKED ISSUE #1930: Memory leak with excessively high levels of exp causes server crash in seconds
#### Issue description
I can crash a Genisys server within seconds with an excessively high level of EXP.

#### Steps to reproduce the issue
- Use /xp to set your exp to an extremely high level of exp, for example /xp 2147483647L @p 
- Quit the server
- Rejoin the server. You'll hang at the "Locating server" terrain. Meanwhile, your server maxes out at 100% CPU and the memory usage spirals upwards at an astonishing rate.
- Look in your terminal.

### The issue here is the exp cache. The exp cache is for a start pointless over-engineering and a terrible premature optimization case. You're caching the calculated exp to reach a certain level, for 2.1 billion levels:
- 1 integer is 32 bits or 4 bytes
- 2.1 billion cached ints = 8.6x10^9 bytes = 8 GIGABYTES of cached integers.

#### Possible solutions
- Remove the exp cache. It's completely pointless, just a waste of memory by holding onto a potentially extremely large quantity of numbers. The processing time it saves is so close to zero it is non-existent. As @SOF3 would say, premature optimization is the root of all evil. In this case, the optimization is over-engineered and has caused major issues. This is the worst case of over-engineered optimization I have seen in a long time.
- Change the calculation and saving of exp so that such calculation is not necessary.
- ~~If the exp cache is to be kept, make it an SplFixedArray of size 32767 to stop it growing to such an astonishing size in this kind of situation.~~ Exp cache is completely pointless.

## I will implement a solution myself. **I open this issue as a warning to whoever did this and hope they learn a lesson.**

I might also point out that this is the second exp-related memory leak I have discovered. Let the person who wrote the exp system hang their head in shame.

#### OS and versions

* Genisys: eb168db
* PHP: 7.0.9 x86
* Server OS: Windows 10 Pro x86
* Game version: Pocket Edition 0.15.7

#### Crashdump, backtrace, memory dumps, plugins list or other files

- xdebug backtrace
```
Fatal error: Out of memory (allocated 136314880) (tried to allocate 234881024 bytes) in C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php on line 1572

Call Stack:
    0.0025     349072   1. {main}() C:\Users\Admin\Downloads\Genisys\src\pocketmine\PocketMine.php:0
    0.1756     454432   2. pocketmine\Server->__construct() C:\Users\Admin\Downloads\Genisys\src\pocketmine\PocketMine.php:467
    2.6756   17142936   3. pocketmine\Server->start() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2035
    2.7451   17244624   4. pocketmine\Server->tickProcessor() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2449
   19.1456   17256920   5. pocketmine\Server->tick() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2571
   19.1456   17256920   6. pocketmine\network\Network->processInterfaces() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2861
   19.1456   17256920   7. pocketmine\network\RakLibInterface->process() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\Network.php:145
   19.1456   17256920   8. raklib\server\ServerHandler->handlePacket() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\RakLibInterface.php:76
   19.1463   17282848   9. pocketmine\network\RakLibInterface->handleEncapsulated() C:\Users\Admin\Downloads\Genisys\src\raklib\server\ServerHandler.php:99
   19.1463   17291136  10. pocketmine\Player->handleDataPacket() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\RakLibInterface.php:140
   19.1463   17291136  11. pocketmine\network\Network->processBatch() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2289
   19.1472   17365248  12. pocketmine\Player->handleDataPacket() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\Network.php:239
   19.1503   17437528  13. pocketmine\Player->onPlayerPreLogin() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2419
   19.1504   17437920  14. pocketmine\Player->processLogin() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2057
   19.1678   17501720  15. pocketmine\Player->calcExpLevel() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2141
   37.9537  133365288  16. pocketmine\Server->getExpectedExperience() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:395

[14:54:48] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[14:54:48] [Server thread/EMERGENCY]: Please upload the "C:\Users\Admin\Downloads\Genisys\crashdumps/CrashDump_Sun_Sep_11-14.54.48-AZOST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```

- Crashdump
```
Genisys Crash Dump Sun Sep 11 14:51:45 AZOST 2016

Error: Out of memory (allocated 278921216) (tried to allocate 469762048 bytes)
File: /src/pocketmine/Server
Line: 1572
Type: E_ERROR

Code:
[1563] 			Server::$sleeper->wait($ms);
[1564] 		}, $microseconds);
[1565] 	}
[1566] 
[1567] 	public function getExpectedExperience($level){
[1568] 		if(isset($this->expCache[$level])) return $this->expCache[$level];
[1569] 		$levelSquared = $level ** 2;
[1570] 		if($level < 16) $this->expCache[$level] = $levelSquared + 6 * $level;
[1571] 		elseif($level < 31) $this->expCache[$level] = 2.5 * $levelSquared - 40.5 * $level + 360;
[1572] 		else $this->expCache[$level] = 4.5 * $levelSquared - 162.5 * $level + 2220;
[1573] 		return $this->expCache[$level];
[1574] 	}
[1575] 
[1576] 	public function about(){
[1577] 		$string = '
[1578] 
[1579] 	§3Genisys§f is a fork of §bPocketMine-MP§f, made by §5iTX Technologies LLC§f
[1580] 	Version: §6' . $this->getPocketMineVersion() . '§f
[1581] 	Target client version: §b' . \pocketmine\MINECRAFT_VERSION . '§f
[1582] 	Source code: §dhttps://github.com/iTXTech/Genisys§f

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
uname -a: Windows NT DESKTOP-4CUH8HC 10.0 build 10586 (Windows 10) i586
PHP version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 4 minutes 4 seconds
Number of loaded worlds: 2
Players online: 0/20

Loaded plugins:
```

### PR DESCRIPTION
**Pull request by dktapps**
### Description

Title sums it up, and #1930 provides a detailed description of the issue. This fixes the **second** exp-related memory leak I've happened onto.
### Reason to modify
- Think twice before modifying: is it the best way? will it break things?
  - It's sure as hell better than the old way of doing it.
- Have you made sure that there is actually a problem before trying to fix it?
  - Hell yes. This replaces some of the most idiotic programming I've seen in years.
- Explain the logic behind your changes - WHY and HOW what you have done works
  - Removed the appalling code causing the memory leak and replaced it with something more efficient.

This PR includes some changes to the API for experience. Various xp-related methods in Player.php have been deprecated in favour of alternatives in Human.php which were already present and waiting to be used. I have bumped the Genisys API to 1.9.2 in response.

The property `experience-cache` has been removed from genisys.yml.
#### Fixes
- Fixed #1930 - excessively high levels of exp in a player caused a huge memory leak which would crash the server in seconds
- Fixed a bug where players would pickup exp even when dead, resulting in apparent loss of dropped exp.
#### Changes
- Various methods in Player.php  and Server.php relating to exp have been deprecated or removed. See the diff for changes.
- Now using the PocketMine API for exp in Human.php (never implemented before now).
### Tests & Reviews

I've tested this in various circumstances, and confirmed that the issues mentioned above no longer occur. I have not however verified with Synapse.

### CODE REVIEW

**Comment by legoboy0215** [comment]
Sorry for going off-topic, but you sound like Simon Cowell now. 

> It's sure as hell better than the old way of doing it.

> Hell yes. This replaces some of the most idiotic programming I've seen in years.

lol

:+1: for the pull :) Sure fixed lots of crashes.

**Comment by dktapps** [comment]
@legoboy0215 I've been influenced by Americans 😆

**Comment by legoboy0215** [comment]
@dktapps Oh noooo...

**Comment by xxFlare** [comment]
@dktapps Awesome. I don't even see a reason of why XP cache should be a thing. It's not on Bukkit servers.

**Comment by dktapps** [comment]
@xxFlare Read my description on #1930

**Comment by legoboy0215** [comment]
Lets see who wrote the XP system...

**Comment by xxFlare** [comment]
@dktapps Already did. I accidentally worded that a bit wrong, but yeah, XP cache is useless.

**Comment by PeratX** [comment]
Tested.
+1

**Comment by ishitatsuyuki** [comment]
+1. lol you triggered manual doc generation.

**Comment by dktapps** [comment]
I forgot to update the Doxygen file.

**Comment by ishitatsuyuki** [comment]
Wait, please also bump for doxygen.

**Comment by dktapps** [comment]
damn, so fast

**Comment by ishitatsuyuki** [comment]
A real +1 this time.

**Comment by PeratX** [comment]
Why not merge @dktapps @ishitatsuyuki

**Comment by dktapps** [comment]
@PeratX The PullApprove resets when somebody pushes another commit. You'll need to re-approve it.

(I could force-merge, but prefer to follow the protocol.)

**Comment by Muqsit** [comment]
+1 tested =D

**Pull request merged**
