### PR TITLE
Fixed batch block updates using BatchPackets

### PR DESCRIPTION
**Pull request by dktapps**
Use `BatchPacket` and stuff all the single `BlockUpdatePacket`s inside it.
This saves DDoSing the client with thousands of single `BlockUpdatePacket`s as per some "fixes".

This restores original behaviour and compensates for the loss of functionality to send multiple block updates in a single packet. I also noticed that with these changes the client actually lags a lot less during large jobs such as world editing jobs.

### CODE REVIEW

**Comment by Muqsit** [comment]
Tested, this fixed my magic carpet plugin <3 +1

**Comment by markkrueg** [comment]
Testing this today. REALLY good. Feels like some dramatic improvements to lag/latency of actions. Even the hotbar seems improved with the batch packets.

**Comment by Muqsit** [comment]
@markkrueg Speaking about the hotbar, it was fixed in this PR: https://github.com/iTXTech/Genisys/pull/1134

**Comment by markkrueg** [comment]
@Muqsit Was that PR not merged into main 10 days ago? How is that PR related to this PR?

**Comment by dktapps** [comment]
@markkrueg I can't imagine why batching produced such a big improvement, but I must admit I've noticed the difference myself.

**Comment by gaoyichuan** [comment]
LGTM, approved

**Pull request merged**
