### PR TITLE
synapse: Update to SPP v5 and update SynLib to 0.2.0

### PR DESCRIPTION
**Pull request by MrGenga**
### Description

Update to SPP v5 and update to SynLib 0.2.0

### Reason to modify

Because old protocol is outdated.

### Tests & Reviews

 I have tested the code and it works. 

SPP v5 is supporting by Nemisys. I update Genisys to SPP v 5. All protocol updates from SynapseAPI is here.

### CODE REVIEW

**Comment by jojoe77777** [comment]
Bad formatting, too many commits, looks unfinished but not sure about that.

**Comment by MrGenga** [comment]
@jojoe77777 it is because I use online editor. And android keyboard doesn't have tab.

**Comment by dschwartz783** [comment]
Just an observation: Have some respect for your code. Don't litter it with nonsensical comments, try to give your commits some sort of significant name to tell us what it's for, don't add on piles of unfinished commits, do not use github's editor to push to GitHub if you plan on editing more than one file, learn how to squash your commits. Sorry for being so critical, but it's tough to watch. :|

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines.

**Comment by dktapps** [comment]
Do stop PR spamming. This one is no better than the last one I closed, which was also below standard.

**Pull request closed without merging**
