### PR TITLE
Dog194 fortune

### PR DESCRIPTION
**Pull request by dog194**
※update for FORTUNE
DiamondOre
CoalOre
EmeraldOre
NetherQuartzOre
LapisOre
All Leaves
Gravel
Potato
Glowstone
Melon
Carrot
Wheat
RedstoneOre
※Update for Silk Touch
Glowstone
GrassPath
※Removed
JUNGLE leaves (drop Cocoa Bean)  My fault

### CODE REVIEW

**Comment by dog194** [comment]
被github网页版吞了不下10个commit。简直坑爹

**Comment by dog194** [comment]
TODO: Nether Wart

**Comment by gaoyichuan** [comment]
Please squash your commits

Code Review -1

**Comment by Muqsit** [comment]
Approved! Code Review -1

**Comment by CrayonDing** [comment]
我认为你下次需要处理下commit数量。 +1

**Comment by dog194** [comment]
+1

**Comment by dog194** [comment]
@Muqsit  Sorry for lots of commit. You can look at files change directly. For some reasons, maybe i will not use git. XD

**Pull request merged**
