### PR TITLE
Update for 0.14.1.

### PR DESCRIPTION
**Pull request by SirGamer**

### CODE REVIEW

**Comment by XShockinFireX** [comment]
0.14.1?

**Comment by SirGamer** [comment]
On Windows 10. :P

**Comment by icsmoke-mcpe** [comment]
Also change protocol maybe?

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
i think protocol + 1

**Comment by SirGamer** [comment]
Yeah, we have to change the protocol. :)

**Comment by Driesboy** [comment]
i was thinking about accepted protocols

**Comment by flaxues** [comment]
This can be closed since @PeratX already added it :P

**Comment by Driesboy** [comment]
yes

**Pull request closed without merging**
