### PR TITLE
Add the missing brewing recipes

### PR DESCRIPTION
**Pull request by dog194**
Added some missing recipes for brewing
 - BREWING_STAND
 - BLAZE_POWDER
 - MAGMA_CREAM
 - FERMENTED_SPIDER_EYE
 - GLISTERING_MELON
 - GOLDEN_CARROT

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Looks good to me!

**Comment by dog194** [comment]
+1 你个 格式强迫症

**Comment by ishitatsuyuki** [comment]
你这英语弱爆了。。。

**Comment by dog194** [comment]
嘛  能知道意思就好 语法时态神马的就随他去吧

**Pull request merged**
