### PR TITLE
Added Support for 0.14.3 (With Updated Protocol!) [TESTED]

### PR DESCRIPTION
**Pull request by CLiu13**
All credit for this solution goes to the original devs who fixed it.

I have not tested this myself yet, but I will do that as soon as I can.

### CODE REVIEW

**Comment by CLiu13** [comment]
Tested it, and everything seems to work fine!

**Comment by Muqsit** [comment]
Thank you and @orlando092 !

**Comment by Muqsit** [comment]
#983 #984

**Comment by Leo3418** [comment]
These edits are incompatible with 0.14.2 and below versions

**Pull request closed without merging**
