### PR TITLE
Fix more than 36 inventory

### PR DESCRIPTION
**Pull request by cre2016**
Players have more than 36 inventory , now can't drop pickaxe .

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Blocking merge by closing. Please explain about this hack.

**Comment by cre2016** [comment]
It is a bug  .When players have more than 36 inventory ,then ,when they pick up item , the item in his hand will be droped by client .

**Comment by ishitatsuyuki** [comment]
And only tools? Really?

**Comment by cre2016** [comment]
We can't find a better way .

**Comment by cre2016** [comment]
all the item in hand .

**Comment by ishitatsuyuki** [comment]
I'm not sure if this is really a client bug.

**Comment by cre2016** [comment]
It is  a bug since PHP5 .

**Comment by ishitatsuyuki** [comment]
You can't find a better way, but hacks like this cannot be merged.

**Comment by cre2016** [comment]
That make player have more than 36 inventory  can mine with less problem .

**Comment by ishitatsuyuki** [comment]
You have to prove that it's a client bug.

**Comment by cre2016** [comment]
A MCPE 's bug .not client .

**Comment by ishitatsuyuki** [comment]
Can you speak English? MCPE is client, Genisys is server.

**Comment by cre2016** [comment]
My mistake .pool Englis .

**Comment by PeratX** [comment]
其实你们可以说中文。

**Comment by cre2016** [comment]
他是谁...

**Comment by cre2016** [comment]
晕....

**Comment by PeratX** [comment]
等下我回去再改吧。

**Comment by ExerciseBook** [comment]
我正想说我们都是中国人

发自我的 iPhone

**Comment by cre2016** [comment]
还得在PlayerInventory重写一个remove

**Comment by ExerciseBook** [comment]
可以直接回复邮件啊。这么6

发自我的 iPhone

**Comment by PeratX** [comment]
我已经修改了BaseImnventory了

**Pull request closed without merging**
