### PR TITLE
Changed Tile to BlockEntity (fully compatible with old APIs)

### PR DESCRIPTION
**Pull request by PeratX**

### CODE REVIEW

**Comment by dktapps** [comment]
+1, tested and everything seems fine. But this is a huge API change.

**Comment by Driesboy** [comment]
please not 
i need to update all the plugins
and players go left genisys

**Comment by dktapps** [comment]
@Driesboy This update is **fully compatible with older APIs**. No changes need to be made to plugins.

**Comment by Driesboy** [comment]
realy?

**Comment by dktapps** [comment]
@Driesboy Yes. Test it if you don't believe me.

**Comment by Driesboy** [comment]
ok i will test

**Comment by PeratX** [comment]
Only for new plugins, I suggest use blockentity instead of tile.

**Comment by gaoyichuan** [comment]
Tested and it worked. Approved.

**Pull request merged**
