### PR TITLE
更新成0.13系列皆可登入

### PR DESCRIPTION
**Pull request by edwinyoo44**
0.14與0.13不一樣
剛剛那個更新在那邊.....Orz......
當初更新到0.14時Network.php有更改，你也沒弄回去

-修復0.13其他版本無法登入問題

### CODE REVIEW

**Comment by PocketKiller** [comment]
@Intyre's work.

**Comment by edwinyoo44** [comment]
What??

**Comment by edwinyoo44** [comment]
That is not work.....................

Than I fix it........................

**Comment by PocketKiller** [comment]
don''t touch buffers... they are right..

**Comment by edwinyoo44** [comment]
you sure?

**Comment by PocketKiller** [comment]
Yes.

**Comment by edwinyoo44** [comment]
Are you run that again?

**Comment by edwinyoo44** [comment]
That is not work

**Comment by PocketKiller** [comment]
That is commited months ago, and Genisys is running smoothly, nothing wrong, works, so you want @shoghicp's one?

**Comment by edwinyoo44** [comment]
This  Network.php and RakLibInterface.php is for 0.14

That can't use for 0.13

**Comment by PocketKiller** [comment]
I am blind while not reading branch name XD sorry.

**Comment by edwinyoo44** [comment]
......

**Pull request merged**
