### PR TITLE
Fixed semi-colon after "Main thread memory"

### PR DESCRIPTION
**Pull request by jojoe77777**
### Description

Replaced the semi-colon after "Main thread memory" (/status) with a normal colon

### Reason to modify

The other lines have normal colons instead, so I assumed this semi-colon was a mistake.
### Tests & Reviews

This isn't code.

### CODE REVIEW

**Comment by dktapps** [comment]
+1

**Comment by Muqsit** [comment]
+1

**Comment by dktapps** [comment]
@muqsit Nice, that was quick :D

**Comment by Muqsit** [comment]
sanic.

**Pull request merged**
