### PR TITLE
Update to 0.15.9

### PR DESCRIPTION
**Pull request by Pub4Game**
### Description

Update to 0.15.9

### Reason to modify

In the new version 0.15.9 mcpe has changed the protocol

### Tests & Reviews

 I have tested the code and it works on my hosting.

### CODE REVIEW

**Comment by SleepSpace9** [comment]
What about the new skins with capes, do they also work or are they causing errors? Did you test?

**Comment by dktapps** [comment]
What actual protocol changes are there?

**Comment by dktapps** [comment]
Holding this for now until I can confirm there are no breaking changes. Master is currently stable.

**Comment by dktapps** [comment]
Rejected, there are breaking changes. You cannot have tested very thoroughly...

**Comment by jjplaying** [comment]
Just rolled it out to my servers, it's working great. Event capes are working, it was just a bug fix update. @dktapps are you sure, you're not mixing it up with 0.16 or 0.15.9 beta?

**Comment by dktapps** [comment]
@jjplaying Try placing/breaking blocks.

**Comment by jjplaying** [comment]
Works for me.

**Comment by dktapps** [comment]
Not for me, hence the closure. Something has changed.

**Comment by jjplaying** [comment]
Okay, that's very strange. I'm on iOS with 0.15.9 from the AppStore, and just updated my server with this PR. So you're sure that you're not mixing it up with 0.15.9 **beta** from Google Play with the new features like command precast?

**Comment by Pub4Game** [comment]
@dktapps iOS MCPE 0.15.9 working fine

**Comment by SleepSpace9** [comment]
Works for me to, in Survival and Creative Mode. I'm on Windows 10 Edition.

**Comment by dktapps** [comment]
@jjplaying of course I'm sure. 0.15.90 changed everything.

@Pub4Game sure, but other platforms aren't.

**Comment by jjplaying** [comment]
Just got an Android device, but can't test it. MCPE simply crashes when i open it :(.

@dktapps There's a 0.15.9 beta when you're in Google Play beta program. That's the new one which isn't released that. And Mojang released a bug 'fix' version (which we're talking about and this PR is about), and also named it 0.15.9, but there are just 'fixes' and capes. Just want to be sure that we're talking about the same.

**Comment by SleepSpace9** [comment]
I can confirm that the released version 0.15.9 on android (Kindle Fire) is working for breaking/placing blocks.

**Comment by jjplaying** [comment]
@SleepSpace9 Me too. Got my android tablet working by deleting the worlds folder, and I can place and break blocks.

**Comment by Pub4Game** [comment]
@dktapps Everything works fine: iOS, Windows 10, unfortunately can't test on Android. Please re-check everything again.

**Comment by PeratX** [comment]
This is 0.15.9 not 0.15.90

**Comment by Pub4Game** [comment]
@PeratX please merge, omg

**Pull request closed without merging**
