### PR TITLE
Fix #1856

### LINKED ISSUE #1856: 3 layers mossy cobblestone in taiga
Mossy cobblestone is found in pieces, not under 2 layers of podzol. The second layer in the taiga also should be dirt, not podzol.

### PR DESCRIPTION
**Pull request by thebigsmileXD**
### Description

Fixing the 3 layers of mossy cobble in taiga underground
Fixing the 2 layers of podzol, changed one to dirt
update from master

### Reason to modify

Its ugly and wrong

### Tests & Reviews

^no idea what this should mean

yea

^uhm works so thats the review

### CODE REVIEW

**Comment by dktapps** [comment]
Wrong branch. Master! :D

**Comment by dktapps** [comment]
This looks fine, but you PRed to the wrong branch. I will cherry-pick this.

**Comment by thebigsmileXD** [comment]
Why to use master and not generator? ;)

**Comment by dktapps** [comment]
Because generator is where PeratX is making a dumb mess.

**Pull request closed without merging**
