### PR TITLE
Add ChickenLayEggSound.php

### PR DESCRIPTION
**Pull request by XFuryMCPE**
### Description

Adds chicken lay egg sound

### Reason to modify

It sounds cool :laughing: 

### Tests & Reviews
Yeah it works.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Yeah you're idiot. No file extensions, and it won't make a sound unless you add some code to trigger it.

**Comment by XFuryMCPE** [comment]
I wasn't trying to add it to the actual chicken, it _was_ so you can trigger it yourself.

**Comment by ZedCee** [comment]
@XFuryMCPE Ask yourself:
- Without a game or user trigger method is this worth it on it's own?
- Could it be done with the plugin that would call it?
- Did I ask if it was worth committing as is?
- Does it follow the require naming schema?

Maybe some of this seems silly, but the goal of Genisys is to make a functional vanilla server without mod like additions.  Any modifications from the Minecraft idiom should likely be done with a plugin.  In the past, many great additions like the mob AI started as a plugin.

**Comment by XFuryMCPE** [comment]
Gotcha @ZedCee , sorry

**Pull request closed without merging**
