### PR TITLE
Fixes Mooshrooms showing as cows

### PR DESCRIPTION
**Pull request by jojoe77777**
Now mooshrooms work properly.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Code review -1
Mooshrooms should extend cows. You may removed important ability.

**Comment by jojoe77777** [comment]
> You may removed important ability.

Can you check if it did? Pretty sure it didn't.

**Comment by ishitatsuyuki** [comment]
Sorry, my fault. This looks good.
Approved.

**Comment by Muqsit** [comment]
+1

**Pull request merged**
