### PR TITLE
LilyPad generation in swamp biome

### PR DESCRIPTION
**Pull request by Muqsit**
Works :3

### CODE REVIEW

**Comment by Muqsit** [comment]
..yeah works!

**Comment by Muqsit** [comment]
The first and the last commits are what you need..

**Comment by PeratX** [comment]
good work

**Comment by NguyenQuangLap** [comment]
One is 0.13. x or not 0.13.1

**Comment by Muqsit** [comment]
@PeratX thanks :D 
I also did some work on spawning pumpkins...but alot of them spawn in so I'll check that and then make a PR

**Comment by NguyenQuangLap** [comment]
May I 0.13 x or is 0.13.1. phar is not @Muqsit

**Comment by Muqsit** [comment]
@NguyenQuangLap php7?

**Pull request merged**
