### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by PeratX** [comment]
No need to remove comment.

**Comment by ishitatsuyuki** [comment]
What does it fix?

**Comment by Pub4Game** [comment]
Clears the array

**Comment by ishitatsuyuki** [comment]
Looks useless. Does it actually change anything?

**Comment by Pub4Game** [comment]
@PeratX Why? It clears the array of => remove unnecessary players in the chunk

**Comment by ishitatsuyuki** [comment]
It doesn't do anything.

**Comment by Pub4Game** [comment]
As you wish...

**Comment by PeratX** [comment]
@Pub4Game First, thank you! Next, $players does not affect any other vars. It is only for send packets. Finally, thank you again :)

**Comment by Pub4Game** [comment]
@PeratX 2333

**Pull request closed without merging**
